### ISSUE TITLE
Triangle mesh for WAVEWATCH III

### ISSUE THREAD

**Issue by jin-liu-prc** [CHLNDDEV/OceanMesh2D#100]
Hi my friend,

I was wondering if OceanMsh2D can generate mesh file that can be read by WAVEWATCH III directly? Or I need to revise the mesh format (fort.14) to fit WAVEWATCH III mesh format (.msh)? Thanks. 

Kind regards,
Jin

**Comment by krober10nd** [comment]
Hello,

Yes, we support that. You can output in the format for ww3 like so: `write(m,'waves','ww3')` where `m` is your `msh` object.

**Comment by jin-liu-prc** [comment]
Many thanks my friend, it's helpful.

**Comment by jin-liu-prc** [comment]
Hi keith, 

Thanks for your help. I was wonder if there is an error in line 41 of OceanMesh2D/@msh/private/writeww3.m? Since opedat.nbdv(i) may be a 2-D matrix which includes open boundary nodes and 0, we may only write open boundary nodes (not 0) into the WAVEWATCH III unstructured file. Thanks. 

Kind regards,
Jin

**Comment by krober10nd** [comment]
Hm, are you referring to case when there's multiple ocean boundaries? 

I'm honestly not sure. I believe the author of that file is Ali Abdolali from August 2018 ali.abdolali@noaa.gov 

We can make a fix to support several open boundaries, sure.

**Comment by jin-liu-prc** [comment]
Thanks Keith, yes, opedat.nbdv (2-D matrix) is multiple ocean boundaries.

**Comment by krober10nd** [comment]
could you test out #103 ?

**Comment by krober10nd** [comment]
Can I go ahead and close this issue @JinLiu1994 ?

**Comment by jin-liu-prc** [comment]
Thanks Keith, the correction is right.
