### ISSUE TITLE
SRTM15+ change version

### ISSUE THREAD

**Issue by oveldg** [CHLNDDEV/OceanMesh2D#102]
SRTM15+ changed version, from v2, to v2.1. You may correct the link in your README.md to: 

ftp://topex.ucsd.edu/pub/srtm15_plus/SRTM15+V2.1.nc

**Comment by WPringle** [comment]
Thank you for the heads-up, we have added change to pull request #101

**Comment by krober10nd** [comment]
#101  has been merged
