### ISSUE TITLE
error in Calc_tau0

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#104]
Hi @krober10nd and @WPringle,

I am following the typical workflow provided in the userguide to create input files (fort.15) for ADCIRC simulation.  When I type the code m = Calc_tau0(m), an error occurs and prompts "No bathymetry data in the grid to calculate the tau0 coefficients". However, I have complete the interpolation by carrying out the previous step m = interp(m, DEMFILE, 'type', 'depth'). In the msh class, the attribute of b is not empty and the value of b is not always 0. I don't know why this happened. The following is my code, 

% Example: Mesh the PRD
clearvars; clc;
addpath(genpath('utilities/'))
addpath(genpath('datasets/'))
addpath(genpath('m_map/'))
%% STEP 1: set mesh extents and set parameters for mesh.
bbox = [111.5 116.5;		% lon_min lon_max
        18 24]; 		% lat_min lat_max
min_el    = 150;  		% minimum resolution in meters.
max_el    = 5e4; 		% maximum resolution in meters. 
max_el_ns = 200;        % maximum resolution nearshore in meters.
grade     = 0.3; 		% mesh grade in decimal percent.
R         = 3;    		% number of elements to resolve feature width.
%% STEP 2: specify geographical datasets and process the geographical data 
%% to be used later with other OceanMesh classes...
dem = 'topo15_compressed.nc'; coastline = 'GSHHS_f_L1';
gdat = geodata('shp',coastline,'dem',dem,'h0',min_el,...
                'bbox',bbox);
    
% NOTE: You can plot the shapefile with bounding box by using the
% overloaded plot command:
%  plot(gdat,'shp'); plot(gdat,'dem');
%% STEP 3: create an edge function class
fh = edgefx('geodata',gdat,...
            'fs',R,'max_el_ns',max_el_ns,...
            'max_el',max_el,'g',grade);
%% STEP 4: Pass your edgefx class object along with some meshing options and
% build the mesh...
mshopts = meshgen('ef',fh,'bou',gdat,'plot_on',1,'nscreen',1);
mshopts = mshopts.build; 
m = mshopts.grd;
% plot(m,'tri');

DT = 2 ; % Stable timestep
TS = '01-Aug-2012 00:00' ; % start time of simulation
TE = '31-Nov-2012 00:00' ; % end time of simulation
DEMFILE = 'topo15_compressed.nc';
BUOYFILE = 'Gridded_N_values.mat';
TPXO9 = 'h_tpxo9.v1.nc';
CONST = 'major8';

m = interp(m, DEMFILE, 'type','depth');
plot(m,'b')

m = CheckTimestep(m,DT);

m = renum(m);

m = make_bc(m,'auto',gdat); % make the nodestring boundary conditions
% plot(m,'bd',0);
% makens(m,'outer',1)   

m = Calc_tau0(m);

Looking forward to your reply.

Best wishes.
Jiangchao

**Comment by krober10nd** [comment]
Hey! 

Could you calculate the min max and mean of m.b and show us?

**Comment by krober10nd** [comment]
Ah I see the problem. You're dem that you use to the build the mesh is called 'dem' but the file you use use to do interpolation is called 'DEMFILE' 

Please make them the same and then it should work.

**Comment by Jiangchao3** [comment]
Hi Keith,

Thanks for your prompt reply. I changed the name of the dem file, but it doesn't work. The error "No bathymetry data in the grid to calculate the tau0 coefficients" appeared again. I calculate the min, max and mean of m.b, they are -302, 3.8382e+03, 4.6100. I think the problem is not in the naming of the dem file. The m.b is not empty and the values of m.b are not always equal to 0. Why is it so strange?

best wishes
Jiangchao

![1](https://user-images.githubusercontent.com/66854878/90246809-f9132280-de67-11ea-8302-c781661e8728.jpg)
![2](https://user-images.githubusercontent.com/66854878/90246815-fadce600-de67-11ea-8ce0-ce05f7cdced9.png)
![3](https://user-images.githubusercontent.com/66854878/90246818-fb757c80-de67-11ea-8ac3-9163d584921e.jpg)
![bath](https://user-images.githubusercontent.com/66854878/90246920-25c73a00-de68-11ea-828f-ad67f895d012.png)

**Comment by krober10nd** [comment]
Quite odd. Could you share the msh so I can see better?

**Comment by Jiangchao3** [comment]
ok, this is the msh file, thanks very much.

[m.zip](https://github.com/CHLNDDEV/OceanMesh2D/files/5074583/m.zip)

**Comment by krober10nd** [comment]
Got it. So it's a problem with the code, not your mesh! A small bug fix is in order. The command `all(obj.b) == 1` only looks at the first value of obj.b, which in your case happens to be 0 so it thinks the whole array is zero incorrectly. 

It should check for any non-zero values like this: `any(obj.b) == 0`

**Comment by krober10nd** [comment]
Ok, I merged in the change in #105. Please git pull the OceanMesh repo on your computer to update.

**Comment by Jiangchao3** [comment]
Yes, when I update the code of Calc_tau0, it works. Thank you very much!

This mesh generation software is very user-friendly, I love it very much. I am recommending my friends to also use it to make their grids. Thanks again.

**Comment by krober10nd** [comment]
That's great to hear! Please keep us posted!
