### ISSUE TITLE
Question about automatically determining the time step

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#114]
hi @krober10nd 

I am confused about the method of automatically determining the time step. 

In Example_3_ECGC, the time step was set to 0.  
![dt](https://user-images.githubusercontent.com/66854878/92458638-40d36280-f1f8-11ea-8963-f28a5c5d3a26.jpg)

When I followed this setting, I found that the time step _dt_ calculated based on the nearshore resolution is very small.
![1](https://user-images.githubusercontent.com/66854878/92459862-cacffb00-f1f9-11ea-8c71-a3327ec5f0c6.jpg)

Therefore, the mesh resolution calculated according to the original code of Example 3 is very small, and it runs very slowly.
![3](https://user-images.githubusercontent.com/66854878/92460615-bf310400-f1fa-11ea-8887-66ffc969759b.jpg)

When I set _dt_ to 2, as in Example_2_NY (Encourage mesh to be stable at a 2 s time step), It turned out to look good.
![4](https://user-images.githubusercontent.com/66854878/92461335-c0aefc00-f1fb-11ea-80ae-976fe7f510be.png)

If using the automatic step size method, is such a small value of _dt_ reasonable to use in the simulation? Or should I specify it myself? 

Best wishes
Jiangchao

**Comment by krober10nd** [comment]
Hey @Jiangchao3 This seems initially at least to be a bug of some sort perhaps when the Courant limiting capabilities were improved #51. I'll take a deeper look into this. 

For now, I'd rather you select the timestep yourself. 

Keep in mind that after make generation is complete, you should check the maximum Courant number for your timestep.

```
max(CalcCFL(m,2.0))
```

and if you still have some problems, you can also bound it after the generation by :

```
m_new = BoundCr(m,2.0); 
```

**Comment by Jiangchao3** [comment]
ok, thanks for your suggestion. I am looking forward to the improvement.

**Comment by Jiangchao3** [comment]
Hi @krober10nd, I have another question about the low-pass filter (or the parameter of 'fl ')

In the userguide, it's said the local Rossby radius of deformation is used automatically for a low-pass filter cutoff:

![2](https://user-images.githubusercontent.com/66854878/92985506-c5b6c880-f4e5-11ea-86cf-f38861652c0d.png)

And in the section of "edgefx: the mesh size function class", the 'fl' is described as 

![1](https://user-images.githubusercontent.com/66854878/92985482-753f6b00-f4e5-11ea-939e-b1f9c3d3697e.png)

In the Example_4_PRVI, a negative value of 'fl' is used as the filter equal to Rossby radius divided by 50:

![5](https://user-images.githubusercontent.com/66854878/92985772-45459700-f4e8-11ea-8439-2c41bc6053fd.jpg)

In the article of "Global Storm Tide Modeling with ADCIRC v55: Unstructured
Mesh Design and Performance", the parameter 'FL' is defined ('FL' is defined by the variable parameter alpha), and three value of 1/80, 1/20, 1/5 was applied to the experiments. 

![3](https://user-images.githubusercontent.com/66854878/92985736-ebdd6800-f4e7-11ea-8763-a35086add942.png)

I am confused about the definition of the parameter 'fl' or 'FL'：

Is the 'fl' in the userguide and the 'FL' in the article the same parameter?

Compare the equation of FL (_L_) in the article with the equation of local Rossby radius in the userguide. The parameter alpha is very special. 
My understanding：if I set  fl=[1,0], the alpha equals to 1, the low-pass filter cutoff is the local Rossby radius. If the value of 'FL'  equals to 1/80 (for example as in the article), I should set the fl = -80, this is a value equals to (local Rossby radius/80). Is that correct?

I wanted to use a system default option. However, when I only set a 'slp' parameter, don't set a 'fl' parameter, 'fl' equals to the default value 0 and it will prompt "INFO: Slope filter is off". This means the low-pass filter is off. If I want to use a system default option, should I use the local Rossby radius and set fl=[1,0]?

Please forgive me for writing so much！I am really confused about this parameter.

**Comment by krober10nd** [comment]
Hey no problem. I'm glad you're inspecting. 

There's two filtering methods: a band or high or low pass filter which is activated with a positive value of 'fl'. A band pass filter is activated with an array of two options i.e low and high pass cutoffs. 

Whereas the negative option instead uses a local Rossby radius of deformation to determine the low pass cutoff instead of having the user arbitrarily select the lowpass value. And in this negative fl case, the LR Radius is divided by the abs(fl). 

Historically we started with just the high and band pass filtering options with the positive fl parameter and that's when we wrote the user guide. Unfortunately we haven't had much time to include some of that new information in the guide. The most update information should be in the help sections in each function. 

I would also want to double check this with @WPringle as he performed the experiments for the paper you're mentioning.

**Comment by krober10nd** [comment]
Hey @Jiangchao3 I updated the user guide to clarify hopefully better the meaning of this `fl` parameter. 

A low pass filter of the bathymetric gradient would be:

```
`fl`, [1e3, 0]
```
or 

```
`fl`, 1e3
```

a band-pass filter of the bathymetric gradient would be: 
```
`fl`, [1e3, 10e3]
```

Low-pass filtering the bathymetric gradient based on the LRR of Deformation dividing the LRR for example by 80 would be: 

```
`fl`,-80
```

I hope this helps, by default all filtering is deactivated. I'm updating the user guide to reflect this fact. 

PS I'm taking a look at the original question in this thread now.

**Comment by Jiangchao3** [comment]
Oh, that's great! Thank you very much for this updating. I think this makes it clearer! 

I have been learning this software for a while and I have to say that it is really a great job. Thanks again!

**Comment by krober10nd** [comment]
Hey @Jiangchao3  thanks for the kind words! 

I appeared to have fixed the issue you brought up in #116 . The bug  had arisen because I built in functionality to not only bound above the maximum Courant number  in the mesh but also bound it below by a constant. The latter is important for implicit ALE type numerical schemes that SCHISM users mainly rely on. In those cases, it's actually necessary to ensure a minimum Courant number. 

However, the intended usage of the automatic timestep selection was originally for ADCIRC models which often run with a semi-explicit numerical scheme.  In this case, I always thought it made more sense to see what's the *maximum* Courant number you can get away with given your finest nearshore resolution.

**Comment by WPringle** [comment]
> Hi @krober10nd, I have another question about the low-pass filter (or the parameter of 'fl ')
> 
> In the userguide, it's said the local Rossby radius of deformation is used automatically for a low-pass filter cutoff:
> 
> ![2](https://user-images.githubusercontent.com/66854878/92985506-c5b6c880-f4e5-11ea-86cf-f38861652c0d.png)
> 
> And in the section of "edgefx: the mesh size function class", the 'fl' is described as
> 
> ![1](https://user-images.githubusercontent.com/66854878/92985482-753f6b00-f4e5-11ea-939e-b1f9c3d3697e.png)
> 
> In the Example_4_PRVI, a negative value of 'fl' is used as the filter equal to Rossby radius divided by 50:
> 
> ![5](https://user-images.githubusercontent.com/66854878/92985772-45459700-f4e8-11ea-8439-2c41bc6053fd.jpg)
> 
> In the article of "Global Storm Tide Modeling with ADCIRC v55: Unstructured
> Mesh Design and Performance", the parameter 'FL' is defined ('FL' is defined by the variable parameter alpha), and three value of 1/80, 1/20, 1/5 was applied to the experiments.
> 
> ![3](https://user-images.githubusercontent.com/66854878/92985736-ebdd6800-f4e7-11ea-8763-a35086add942.png)
> 
> I am confused about the definition of the parameter 'fl' or 'FL'：
> 
> Is the 'fl' in the userguide and the 'FL' in the article the same parameter?
> 
> Compare the equation of FL (_L_) in the article with the equation of local Rossby radius in the userguide. The parameter alpha is very special.
> My understanding：if I set fl=[1,0], the alpha equals to 1, the low-pass filter cutoff is the local Rossby radius. If the value of 'FL' equals to 1/80 (for example as in the article), I should set the fl = -80, this is a value equals to (local Rossby radius/80). Is that correct?
> 
> I wanted to use a system default option. However, when I only set a 'slp' parameter, don't set a 'fl' parameter, 'fl' equals to the default value 0 and it will prompt "INFO: Slope filter is off". This means the low-pass filter is off. If I want to use a system default option, should I use the local Rossby radius and set fl=[1,0]?
> 
> Please forgive me for writing so much！I am really confused about this parameter.

Hi @Jiangchao3, thanks for going through our user guide and the ADCIRC v55 paper in detail. What you have written and what @krober10nd confirmed is correct about the negative fl option where it is a fraction of Rossby radius length. The way I wrote the equation and the number in the article was alpha as a fraction, e.g., 1/80. But in reality that actual fl used as input to oceanmesh2d is fl = -80 for this case. 

@krober10nd, I see where you updated the edgefx properties of fl, I also updated the text in Section 3.5 of user guide and added the latest user guide to the static version on ResearchGate.

**Comment by Jiangchao3** [comment]
@krober10nd Thanks for your work. I have merged the updating code into my branch forked from you. I tested the example 3 again, it displayed the same _dt_ as you did. I will follow your suggestion that sees what's the maximum Courant number after using the automatic timestep for my case.

@WPringle Thanks for your reply. I have clearly understood the meaning of the parameters 'fl' or 'FL' under your and @krober10nd's explanation. Thanks for your discussion about the combination of parameter ‘slp' and 'fl'. I am setting my parameters according to your suggestions.

**Comment by Jiangchao3** [comment]
Hi @krober10nd, the automatic timestep was calculated as 5.1048s for my case, when I do the calculation of CalcCFL and BoundCr, the _dt_ should be set to 5.1048, otherwise, there will be very strange results.
when I use the script:
CFL = CalcCFL(m);
min(CFL)
max(CFL)
the result was: 
![1](https://user-images.githubusercontent.com/66854878/93016034-c1c39d00-f5f0-11ea-8532-28f4196cd25e.png)
However, the userguide describe: 
![2](https://user-images.githubusercontent.com/66854878/93016079-1830db80-f5f1-11ea-8957-6cb5d9a8309f.jpg)

when I use the script:
dt = fh.dt;
CFL = CalcCFL(m,dt);
min(CFL)
max(CFL)
m = BoundCr(m,dt);
Everything is ok!

So I think it is necessary to specify a timestep (using the value of fh.dt) when checking the Cr.

**Comment by krober10nd** [comment]
Hm that's strange. Are you using the SRTMv2.1 for the DEM in the bigger box?

In any case, bounding the CFL at the mesh sizing stage normally isn't sufficient which is why msh.BoundCr has to exist. That will guarantee the Cr exist is enforced by iteratively adapting mesh resolution.

**Comment by Jiangchao3** [comment]
I use the topo15_compressed for the DEM. I also tested the Example3_ECGC, when I calculate the CFL by typing: 

CFL = CalcCFL(m)

the same strange display again, the max CFL=2631, the min CFL=2.4366

However, the CFL should be < 0.5, isn't it?

I think the problem may not be about the DEM file and maybe here:
![1](https://user-images.githubusercontent.com/66854878/93018338-a319d200-f601-11ea-897a-6dd0fa3c3214.jpg)
The nargin of the above strange case = 1, the code executes the 'else' branch.
If it is CalcCFL(m, fl.dt), the code will execute the first branch and the _dt_ equals to the fl.dt. this case is ok.

So I think it is necessary to specify a timestep (using the value of fh.dt) when calculating the CFL, but why  the user guide say: "If you don’t pass it a _dt_ it will output the theoretical maximum possible stable dt in the domain given the mesh
size."

And a further question, in example_3, there are two bbox. the automatic timestep of the outer domain is 6.2979 seconds and the automatic timestep of PostSandyNCEI domain is 1.1134 seconds. How to perform the CalCFL and BoundCr? There are two timestep but only one _msh_ file.

**Comment by krober10nd** [comment]
> I use the topo15_compressed for the DEM. I also tested the Example3_ECGC, when I calculate the CFL by typing:

Yea, I would expect differences given that you're using a different DEM than I did (I used SRTMV2.1).

> So I think it is necessary to specify a timestep (using the value of fh.dt) when calculating the CFL, but why the user guide say: "If you don’t pass it a dt it will output the theoretical maximum possible stable dt in the domain given the mesh
size."

Ah ok. Yes, you should specify the stable timestep  that was output to the screen when you call `msh.CalcCFL` (as the second input argument).  That second branch in `msh.CalcCFL` where it calculates the maximum theoretical timestep should be either improved or removed IMO @WPringle . This actually isn't the first time this issue has been brought up. 


> And a further question, in example_3, there are two bbox. the automatic timestep of the outer domain is 6.2979 seconds and the automatic timestep of PostSandyNCEI domain is 1.1134 seconds. How to perform the CalCFL and BoundCr? There are two timestep but only one msh file.

So then in this case with the high resolution zone around NY, you're numerically restricted by your finest resolution since the mesh is seamless. The multiscale meshing technique is to enable the usage of vastly different horizontal resolution DEMs to be utilized in the same meshing process at the same time.

**Comment by Jiangchao3** [comment]
Oh, I understand. Even if two automatic timesteps are calculated separately, only the smaller one will be used in the simulation, so just take this smaller value into the calculation of CalCFL and BoundCr using the multiscale mesh. It's great! Thank you @krober10nd!

**Comment by Jiangchao3** [comment]
Hi @krober10nd and @zcobell 

First of all, thank you very much for your timely participation in my previous issues. This is of great help to my learning.

Now, I have met the error 'ERROR: Elevation.gt.ErrorElev, ADCIRC stopping'. 

![3](https://user-images.githubusercontent.com/66854878/93658429-19895a80-fa6e-11ea-8cd3-07b516ef82cd.png)

Obviously, the ELMAX value of the final two timesteps exceeded the threshold 1000, which caused the simulation to terminate. I noticed this issue has been mentioned on the official website.

![1](https://user-images.githubusercontent.com/66854878/93658508-9b798380-fa6e-11ea-9ec4-e7ad0bf9f9f0.jpg)

In the listserv of ADCIRC, someone also raised this question, and there is some discussion. 

![1](https://user-images.githubusercontent.com/66854878/93658558-383c2100-fa6f-11ea-9167-4ae43d277a3b.png)

However, my mesh was generated by the tool of OceanMesh2D, and I checked the CFL after the generation.  

Is this phenomenon caused by grid instability? Where should I make changes to fix this error? I think this may be a common problem encountered by model beginners during their first simulation. But I have no idea to solve this problem.

Here are my script and code. I would be very grateful if you can give me some advice.

[PRD.zip](https://github.com/CHLNDDEV/OceanMesh2D/files/5249079/PRD.zip)

**Comment by krober10nd** [comment]
Hey @Jiangchao3 non fatal and fatal instabilities are common however you build the mesh. Our tools try to minimize this but nothing is ever perfect. 

One thing to check is sharp gradients in bathymetry, which can be done with the method lim_bathy_slope. 

Besides that it could also be how you set up your model (the model parameters) 

Have you looked at the instability and checked the bathymetry there? Data is never perfect as well.

**Comment by krober10nd** [comment]
Also if you could, please use the latest srtm v2.1 to build with. The older ones had many more pits and holes in the DEM and often did not align with the gshhs shoreline.

**Comment by krober10nd** [comment]
I took a look at your mesh and script. I noticed that it's prescribing ocean boundaries pretty close to land. This is often a problem.

You may want to lower the depth threshold for automatic boundary prescription like so...

```
m = make_bc(m,'auto',gdat,'depth',50); 
```

This will only label ocean boundary if they're below 50 m deep. Regional ocean boundary placement is a delicate issue.  Keep in mind, the domain does not have to be a box and can be any polygonal shape as long as the polygon is closed.

You may want to consider shaping the outer domain so that this is not a problem (if it is in the first place).
<img width="1440" alt="Screen Shot 2020-09-19 at 11 49 38 AM" src="https://user-images.githubusercontent.com/18619644/93670061-b21fda80-fa6e-11ea-9a8e-298e3402552f.png">

**Comment by Jiangchao3** [comment]
Oh thanks, your reply is always so timely and helpful. I will conduct some experiments based on your suggestions to see where the problem is.

**Comment by krober10nd** [comment]
I think this kind of communication would better off in a slack channel, so I created one here...

oceanmesh2d.slack.com

@WPringle  lets update the README to indicate this.

**Comment by krober10nd** [comment]
https://join.slack.com/t/oceanmesh2d/shared_invite/zt-hcu2nag7-NUBw52cxxlYupLrc1hqvhw

**Comment by WPringle** [comment]
@Jiangchao3, so the question you asked pertains mainly to ADCIRC although I agree OceanMesh2D has been made primarily for ADCIRC application. Check the following channel for my answer: https://oceanmesh2d.slack.com/archives/C01BDJBGKUH
