### ISSUE TITLE
Smooth outer does nothing

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#118]
* Minimal working example

```
bbox = [0, 1; 0,1]; 
boubox = [0,0; 1,0; 1,1; 0,1; 0,0; NaN NaN ];
min_el = 1e3; 

gdat1 = geodata('pslg',boubox,'bbox',bbox,'h0',min_el);
fh1 = edgefx('geodata',gdat1,'g',0.15);

bbox2 = [-1, 2; -1,2]; 
boubox2 = [-1,-1; 2,-1; 2,2; -1,2; -1,-1; NaN NaN ];
min_el2 = min_el*5; 

gdat2 = geodata('pslg',boubox2,'bbox',bbox2,'h0',min_el2);
fh2 = edgefx('geodata',gdat2,'g',0.10);

mshopts = meshgen('ef',{fh2, fh1},'bou',{gdat2,gdat1},'plot_on',1,'itmax',5,'cleanup',0);
mshopts = mshopts.build;

m = mshopts.grd; 
plot(m)
```

Whether or not I comment out the call to `smooth_outer` in `meshgen` produces the same results. There should be a smooth transition out of the nest.

![withou_smooth_outer](https://user-images.githubusercontent.com/18619644/95663861-04f22c80-0b19-11eb-8f10-e3a3515adbc7.png)

**Comment by krober10nd** [comment]
* Edge function is indeed smoothed but it appears not to be used inside the generation of the mesh. 
![after_smoothed](https://user-images.githubusercontent.com/18619644/95663901-78943980-0b19-11eb-9105-ad92aca12135.png)

**Comment by WPringle** [comment]
Interesting, I guess we only tested the result of the smooth edgefx in detail. I'll test your example out.

**Comment by krober10nd** [comment]
Yea the outer box doesn't get the correct initial points especially near the inner nest even despite its sizing function having this variation in it.

**Comment by WPringle** [comment]
It does work if you do enough iterations. There was a bug in dpoly #119 btw that caused it to crash when it did more iterations. At 10 iterations it does the delete close points and starts to work.

**Comment by krober10nd** [comment]
Yea but that’s relying on the mesh adaptation. Shouldn’t the initial point distribution follow the variations in the sizing function?

**Comment by krober10nd** [comment]
We should create several of these tests.

**Comment by WPringle** [comment]
> Yea the outer box doesn't get the correct initial points especially near the inner nest even despite its sizing function having this variation in it.

Hmm yeah I see it should delete some of them initially based on the edgefx. I'll take a look at this too.

**Comment by WPringle** [comment]
> > Yea the outer box doesn't get the correct initial points especially near the inner nest even despite its sizing function having this variation in it.
> 
> Hmm yeah I see it should delete some of them initially based on the edgefx. I'll take a look at this too.

Oh now I get it. Yeah so the h0 of the outer is larger than the edgefx value in the smoothed region so it can't be distributed more finely.

**Comment by krober10nd** [comment]
Yea so then the h0 should be determined after smooth outer is called ay

**Comment by WPringle** [comment]
Yeah if I re-update the h0 for the outer to be equal to the minimum of the ef then I get this:

![image](https://user-images.githubusercontent.com/21131934/95666701-c2811d80-0b21-11eb-8155-45e857e51716.png)

**Comment by krober10nd** [comment]
Yea and what happens if you shrink the inner grade?

**Comment by WPringle** [comment]
That wouldn't affect anything, the grade would go by the outer one

**Comment by krober10nd** [comment]
Shouldn't it go by the minimum grade?

**Comment by krober10nd** [comment]
In theory we could enforce variable grade only in their respective boxes

**Comment by krober10nd** [comment]
Okay, so I make the initial point formation/rejection use the minimum of all h0 
```
        disp(['    for box #' num2str(box_num)]);
                    % checking if cell or not and applying local values
                    h0_l = min(obj.h0);
                    max_r0 = 1/h0_l^2;   
```

>> That wouldn't affect anything, the grade would go by the outer one

And my my observations contradict this. 

* Inner box grade set to 0.15 (outer box grade 0.15)

![Innergrade15](https://user-images.githubusercontent.com/18619644/95667012-7e4c4800-0b36-11eb-95cc-ab844e940f36.png)

* Inner box grade set to 0.05 (outer box grade 0.15)

![Innergrade05](https://user-images.githubusercontent.com/18619644/95667014-83a99280-0b36-11eb-8f59-2c7e8498e59f.png)

.

**Comment by krober10nd** [comment]
~~^ This result is also not because the initial point distribution is correct either. The periodic mesh improvement causes it to smooth out.~~

**Comment by krober10nd** [comment]
Nevermind I got it. I'll add it to the dpoly_patch PR
