### ISSUE TITLE
gdat plot

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#129]
* plotting the DEM with no shoreline results in a blank figure. 

```
dem = geodata('dem',DEMNAME,'h0',min_el); 
plot(gdat,'dem');
```

**Comment by WPringle** [comment]
I didn't know the geodata with only dem input would even work. Does that just load in the DEM?

**Comment by krober10nd** [comment]
yep. I do it sometimes if I want to interpolate a bunch  of DEMs.

**Comment by krober10nd** [comment]
So this can be easily fixed by removing the `inpoly` calls when calling `plot(gdat,'dem')` without a shoreline.
