### ISSUE TITLE
variant newline styles

### ISSUE THREAD

**Issue by HamishB** [CHLNDDEV/OceanMesh2D#141]
Hi,

don't know if you care, but the following files have a mix of Mac OS9 and DOS newline characters in them. 'mac2unix' or 'dos2unix' command line tools will convert them.

```
git$ file `find .` | grep terminators
./@geodata/private/fastsmooth.m:                                        ASCII text, with CR line terminators
./@geodata/geodata.m:                                                   C++ source, ASCII text, with CRLF line terminators
./utilities/GEOM_UTIL/mesh-cost/triarea.m:                              ASCII text, with CRLF line terminators
./@meshgen/meshgen.m:                                                   C++ source, ASCII text, with CRLF line terminators
```

towards perfection,
Hamish

**Comment by krober10nd** [comment]
hm never heard of "newline" style. what's the implication of this?

**Comment by HamishB** [comment]
MacOS9 and earlier used '\r' (CR) to indicate a newline in a text file, UNIX and Mac OSX use '\n' (LF), DOS/Windows uses '\r\n' (CRLF). Most industrial strength text editors will detect and deal with it automatically (Microsoft Notepad being a ridiculous exception; Microsoft Excel on a Mac saves .csv files with the old CR linefeed which everyone else abandoned a decade ago). Try opening `@geodata/private/fastsmooth.m` with `less` or `vi` and you'll experience some weirdness.

see also https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats

**Comment by krober10nd** [comment]
so how do I fix that? Is there some one liner to clean up all the files?

**Comment by zcobell** [comment]
`dos2unix` usually does the trick on Unix-type systems. You can tell git to give you the right type for your specific system using:
```
git config --global core.autocrlf true
```
