### ISSUE TITLE
logo?

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#152]
* After several years of development, I think this package deserves a logo. 
* I propose: OceanMesh2D with two triangles for the M?

**Comment by WPringle** [comment]
Sure, if you come up with a design post it here. I was also thinking this based on the last slide of that talk showing all the logos.

**Comment by krober10nd** [comment]
<img width="771" alt="Screen Shot 2020-12-03 at 8 37 56 PM" src="https://user-images.githubusercontent.com/18619644/101101871-8a3d0f00-35a7-11eb-8f10-732a344117d8.png">

**Comment by HamishB** [comment]
I'm wondering if you could make a triangle shapefile (triangular holes) and run that through OM2D, so there'd be many smaller triangles within the two big ones and the OM2D software would have created part of its own logo.

**Comment by krober10nd** [comment]
<img width="766" alt="Screen Shot 2020-12-03 at 10 19 21 PM" src="https://user-images.githubusercontent.com/18619644/101109413-a21b8f80-35b5-11eb-8b82-264b11efd272.png">

```
clearvars; close all; clc;
%%
% Make a triangle for the logo
pslg= [
    0.2252    0.2226
    0.4418    0.6664
    0.6676    0.2226
    0.2252    0.2226
    NaN NaN];


gdat = geodata('bbox',[0,1;0,1],'pslg',pslg,'h0',500,'window',1);

gdat.inpoly_flip = 1;

fh = edgefx('geodata',gdat,...
    'fs',2);

mshopts = meshgen('ef',fh,'bou',gdat,'plot_on',1,'nscreen',1);
mshopts = mshopts.build;

m = mshopts.grd;

plot(m,'tri',0);

print -dpng -r300 triangle_for_logo

%%
% Make a meshed o
x = 0.5; y = 0.5; 
r =  0.1 ;
th = 0:pi/50:2*pi;
xunit = r * cos(th) + x;
yunit = r * sin(th) + y;

pslg = [xunit', yunit'; NaN NaN]; 

gdat = geodata('bbox',[0,1;0,1],'pslg',pslg,'h0',500,'window',1);

gdat.inpoly_flip = 1;

fh = edgefx('geodata',gdat,...
    'fs',2);

mshopts = meshgen('ef',fh,'bou',gdat,'plot_on',1,'nscreen',1);
mshopts = mshopts.build;

m = mshopts.grd;

plot(m,'tri',0);

print -dpng -r300 o_for_logo
```

**Comment by krober10nd** [comment]
<img width="744" alt="Screen Shot 2020-12-03 at 10 22 07 PM" src="https://user-images.githubusercontent.com/18619644/101109603-076f8080-35b6-11eb-81b3-b6dcd000d269.png">

**Comment by HamishB** [comment]
Since the area within the letters is small, maybe draw a rectangle around everything and fill the space between the bbox and the outside of the letters with triangles, and then leave the letters solid black?

**Comment by HamishB** [comment]
If lettering is saved as .svg in Inkscape or similar you can get the coords of the letters from inside the .svg text file. Maybe extracting from PostScript is easier as svg might be using bezier curves to define the boundaries of the letters?

**Comment by HamishB** [comment]
In GRASS: import png with r.in.gdal, then r.to.vect to get polylines of lettering, then v.out.ogr to get a shapefile of the boundaries

**Comment by krober10nd** [comment]
maybe @HamishB you can try to do what you're suggesting and post it in #153 ?
