### ISSUE TITLE
gdat DEM extending to north-east corner of bbox, extrapolating beyond netCDF

### ISSUE THREAD

**Issue by HamishB** [CHLNDDEV/OceanMesh2D#155]
This may just be a rendering issue or real but not harmful as happening outside of the region of interest, but FYI in playing around with a simple rectangular representation of the Black Sea I notice that if my bbox extends beyond the extent of the netCDF DEM then when plotted with plot(gdat, 'dem') the DEM is shown to extend to the north and eastern bounds of the bbox, even when that is far beyond the coverage of the netCDF data. The DEM data seems to be in the right place.

![dem_ne](https://user-images.githubusercontent.com/244324/101439783-284f2180-397a-11eb-92e8-d2286df1f4f9.png)

data files to recreate in this .zip file:
[test_sea.zip](https://github.com/CHLNDDEV/OceanMesh2D/files/5656838/test_sea.zip)

code for creating the synthetic test DEM and coastline and then meshing with OM2D follows.

OM2D:
```
%% simplified Black sea-like basin
clear all, close all, clc

BBOX = [ 27.75 41.25 + 0.75; 41.25 45.25 + 0.75];

% ?? if defined this way does not plot light as green line with plot(gdat, 'shp')  ??
COASTLINE = [ ...
 28.0 41.5
 28.0 45.0
 41.0 45.0
 41.0 41.5
 28.0 41.5
 NaN NaN
];

DEM       = 'test_basin2k.nc';
COASTLINE = 'basin_box'  % .shp

DT        = 2.0;        % DESIRABLE STABLE TIMESTEP
MIN_EL    = 10e3;       % MINIMUM MESH RESOLUTION IN METERS
FS        = 3;          % NUMBER OF POSSIBLE ELEMENTS ACROSS CHANNEL WIDTH
MAX_EL    = 500e3;
MAX_EL_NS = 50e3;      % MAXIMUM ELEMENT SIZE NEARSHORE
SLP       = 10;         % NUMBER OF NODES PER GRADIENT OF BATHY
GRADE     = 0.10;


gdat = geodata('shp',COASTLINE,...
     'dem',DEM,...
     'bbox',BBOX,...
     'h0',MIN_EL);

fh = edgefx('geodata',gdat,...
    'fs',FS,...
    'max_el_ns',MAX_EL_NS,...
    'max_el',MAX_EL,...
    'slp',SLP,...
    'g',GRADE,...
    'dt',DT);

plot(gdat, 'dem')
%plot(gdat, 'omega')
%plot(gdat, 'shp')


%% BUID MESH
mshopts = meshgen('ef',fh, 'bou',gdat, 'plot_on',1);
m = mshopts.build.grd;

plot(m, 'tri')

m = interp(m, gdat);
m = lim_bathy_slope(m, 0.10);
m = BoundCr(m, 2.0);
m = renum(m);

plot(m, 'bmesh')
```

Commands in GRASS to create the test DEM and coastline:
```
# create netCDF DEM in GRASS

# set up bounding box
g.region s=41.5 n=45.0 w=28.0 e=41.0 res=0:01 -ap
g.region save=domain

# zoom in by 0.75 degree
g.region s=s+0.75 n=n-0.75 w=w+0.75 e=e-0.75

# create a pit
r.mapcalc "one = 1"
eval `g.region -cg`
  #center_easting=34.50
  #center_northing=43.25
r.cost -k in=one output=cone coord=$center_easting,$center_northing --o

# zoom back
g.region domain

# add a floodplain border
eval `r.info -r cone`
r.mapcalc "basin = -1 * if(isnull(cone), 1.0, 1 + ($max - cone)*6.5)"
r.colors basin color=haxby

# export as netCDF
r.out.gdal in=basin out=test_basin2k.nc format=netCDF

# coastline
v.in.region basin_box
v.out.ogr in=basin_box dsn=basin_box.shp format=ESRI_Shapefile

# if you want two column x,y boundary data for coord defined coastline:
# v.out.ascii basin_box format=standard
```

**Comment by krober10nd** [comment]
Hamish, thanks..if the coastline is a NaN delimited vector, then pass it to the geodata class with the pslg option. I think this is discussed in the guide. Anyway when it plots, it does linear interpolation to the extents of the bbox. 

If the user created or had used data that isn't covering the entire area and wanted to mesh, then that's a user error imo.
