### ISSUE TITLE
Error in specifying riverine boundary segments!

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#166]
Hey, @CHLNDDEV and @krober10nd , I encountered a problem when making boundary conditions. I tried to add a flux boundary (riverine flow), as shown in the first figure. There are two triangles and three vertices on the left side. The number of the three vertices are marked aside, as shown in the second figure. When I set 1183 for the value of vstart and set 1182 for the value of vend, the result is as shown in the third figure. When I set 1183 for the value of vstart and set 1167 for the value of vend, it went wrong as shown in the fourth figure. I want to know how to set the river boundary correctly. I noticed that there is no detailed description in the userguide or the previous discussions. Many thanks to you!

![image](https://user-images.githubusercontent.com/66854878/103007425-5f265980-456e-11eb-89c1-17bc30b17f9e.png)

![image](https://user-images.githubusercontent.com/66854878/103007438-651c3a80-456e-11eb-8f37-adf3f6788620.png)

![image](https://user-images.githubusercontent.com/66854878/103007446-69e0ee80-456e-11eb-9421-7a1d83615547.png)

![image](https://user-images.githubusercontent.com/66854878/103007452-6e0d0c00-456e-11eb-9fcf-41738e028be4.png)

**Comment by WPringle** [comment]
I also encountered this before but would good to find out exactly what is causing this. What happens when you set the third entry to 0?

**Comment by krober10nd** [comment]
Yes, the last segment needs to be flipped with order=1 but should work with order 0. Echoing William's comments, I'd like to see what happens.

**Comment by krober10nd** [comment]
This fix was merged in. Please let me know how it works!

**Comment by Jiangchao3** [comment]
Yes, now it does work well! Thank you very much!

![image](https://user-images.githubusercontent.com/66854878/103057521-ac401500-45da-11eb-8304-8f33b5902dd9.png)

**Comment by Jiangchao3** [comment]
hi, @krober10nd , when I use the command make_bc(m,'outer',1), the result is always right as shown in the figure above, no matter setting the vstart=1183 vend=1182 or setting the vstart=1182 vstart=1183. However, when I use the command make_bc(m,'outer',0), no matter setting vstart=1183 vend=1182 or setting the vstart=1182 vend=1183, the result is shown as the figure below:

![QQ图片20201224115640](https://user-images.githubusercontent.com/66854878/103059116-25da0200-45df-11eb-9507-14a50edc00dd.png)

So, I don't understand the meaning of the direction of clockwise and anti-clockwise.

![image](https://user-images.githubusercontent.com/66854878/103059278-9aad3c00-45df-11eb-9ff6-1eb8fb1404eb.png)

**Comment by krober10nd** [comment]
I’m not sure what you’re saying. If the boundaries are correctly labeled with the first option, why bother with the other option?

**Comment by Jiangchao3** [comment]
Yes, you are right, I just have a try with a curiosity.
