### ISSUE TITLE
Making the f.20 file!

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#168]
Hi, @krober10nd and @WPringle, I have written several Matlab scripts for making the f.20 file according to the suggestion from the slack channel.  My riverine data is the volume flow (m3/s), and in an excel format (see the test..xlsx). The file Riverflux_distribution is used to calculate the representative edge width and the distribution percentage of each node on the river boundary.  The Make_f20_mycode file can be used to calculate the q (m2/s) for each node on the river boundary. In my testing case, I set five riverine flow boundaries (ibtype=22), and each boundary has three nodes. I noticed that there is not a writefort20 file in the msh/private folder. 

The Make_f20_mycode can work smoothly, but I can not write the f.20 file yet, maybe somewhere is wrong.

![image](https://user-images.githubusercontent.com/66854878/104027737-c6950800-5202-11eb-8152-cafd15c29460.png)

Can you help me improve these scripts to make the f.20 file successfully? I feel sorry that I can not put all my data on the website because of our regulation, if you need these data, I can send them to you privately by email. Or, I think it may be a good idea that gives an example_12 for guiding to make the f.20 file with some open data.

Thanks very much, and best wishes to you!
[f20.zip](https://github.com/CHLNDDEV/OceanMesh2D/files/5787732/f20.zip)

**Comment by krober10nd** [comment]
Hey @Jiangchao3 sure thing I can. 

 But could you please start a pull request with these changes so we can use the version control software to analysis the code changes more easily?

**Comment by Jiangchao3** [comment]
Yes, let me try to start a pull request.

**Comment by Jiangchao3** [comment]
Hey, @krober10nd, I have created a new pull request. Although I have used the GitHub desktop software for a long time, it is the first time to create a pull request. Nice and convenient tool!

**Comment by krober10nd** [comment]
#169
