### ISSUE TITLE
Directional wind stress nodal attribute

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#173]
* We need support for reading this attribute into OM and writing.
* Also, support for mapping between two meshes to facilitate minor connectivity changes (similar to other f13 nodal attributes).

**Comment by WPringle** [comment]
- We do not have ability to compute this attribute but it can be read in from existing fort.13 and written out (I have been doing this with HSOFS mesh)
- The map_mesh_properties msh method already handles your second point.

**Comment by krober10nd** [comment]
Ok then less work to do. Although would be nice to plot it

**Comment by WPringle** [comment]
try the arbitrary f13 plotter just type in 'dir' and it will find it. It will then plot the infinity norm of it

**Comment by krober10nd** [comment]
yes, this worked great. 

<img width="1440" alt="Screen Shot 2021-01-14 at 11 49 54 AM" src="https://user-images.githubusercontent.com/18619644/104606549-a203ba80-565e-11eb-8cf2-0e8845305779.png">
