### ISSUE TITLE
OceanMesh2D\utilities\split.m conflict

### ISSUE THREAD

**Issue by Onur-Kurum** [CHLNDDEV/OceanMesh2D#197]
split.m in utilities does not work with other codes trying to use Matlab's own split.m 
Only work around I found is the remove OM2D from Matlab's path when I am not using OM2D

**Comment by krober10nd** [comment]
Thanks @Onur-Kurum  @WPringle suggest renaming to `split_bars.m` ?

**Comment by krober10nd** [comment]
#198
