### ISSUE TITLE
undefined 'slope_calc' in GridData.m

### ISSUE THREAD

**Issue by HamishB** [CHLNDDEV/OceanMesh2D#208]
Hi,

running `m = interp(m, {gdat1}, 'type', 'slope')` gives an error for the disp() on line 132 of @msh/private/GridData.m as 'slope_calc' is undefined. Commenting out the disp() lets it continue & complete without further error.

thanks,
Hamish

**Comment by krober10nd** [comment]
Thanks. We will fix it. But please do not do Interpolation from gdat objects as we’ve discussed many times already.

**Comment by HamishB** [comment]
Understood about interpolating gdat objects. In this case I was using it for generating offshore/deep water slopes for Calc_IT_Fric() so wasn't too concerned with subsampling problems as the elements are large out at sea compared to the raster netcdf bathy cell size.

**Comment by krober10nd** [comment]
Okay cool..because nearshore it creates a ton of problems as it can create artificial topo-bathymetric holes. 

If you want a quick fix for this just specify the kwarg `slope_calc` there. I believe `rms` is the default option...This should by pass the error for now.

**Comment by WPringle** [comment]
See #207 for fix
