### ISSUE TITLE
fort.15 cosmetics

### ISSUE THREAD

**Issue by HamishB** [CHLNDDEV/OceanMesh2D#21]
Hi,

two small cosmetic issues with the generation of the fort.15 files, the first is mostly cosmetic, the second has functionality implications.

1) @msh/private/writefort15.m
```
diff --git a/@msh/private/writefort15.m b/@msh/private/writefort15.m
index 0d536df..6e108a0 100644
--- a/@msh/private/writefort15.m
+++ b/@msh/private/writefort15.m
@@ -148,7 +148,7 @@ end
 % Open boundary harmonic forcing  
 for k = 1: f15dat.nbfr
     fprintf(fid, '%s \n', f15dat.opealpha(k).name  ) ; 
-    fprintf(fid, '%16.9e %16.9e \n', f15dat.opealpha(k).val' ) ; 
+    fprintf(fid, '%16.9e %16.10g \n', f15dat.opealpha(k).val' ) ; 
 end
 
 %  ANGINN
```

The phase angle is given in engineering style, which makes it annoying to parse as regex in Perl. As engineering units are nice for values which vary over many orders of magnitude, but don't really add much for values which are evenly distributed over the range of 0-360, it's nice for humans reading it to see the regular floating point representation and easier to parse as well.
%16.10g preserves all the precision of %16.9e.
I don't know if anyone else beyond me has to deal with the Perl regex matching, but the human readability aspect might make the change of general interest.

2) utilities/Make_f15.m
```
diff --git a/utilities/Make_f15.m b/utilities/Make_f15.m
index 1893f37..aad52be 100644
--- a/utilities/Make_f15.m
+++ b/utilities/Make_f15.m
@@ -192,7 +192,7 @@ obj.f15.dtdp = dt ;
 % Runday
 obj.f15.rndy = datenum(te)-datenum(ts);
 
-obj.f15.extraline(10).msg = ts;
+obj.f15.extraline(10).msg = datestr(ts, 'yyyy-mm-dd HH:MM:SS UTC');
 
 % Checking f11
 if ~isempty(obj.f11)
```

The `ts` and `te` time variables are suggested to be in the format of `'01-Jan-2018 03:00'` in the Make_f15.m header-help and LaTeX docs* and that gets written to the NetCDF footer in fort.15. The parameter notes at adcirc.org state:
```
NCDATE = The format of NCDATE must be as follows so that ADCIRC can create netcdf files that comply with the CF standard: yyyy-MM-dd hh:mm:ss tz. For example, if the cold start date/time of the run is midnight UTC on 1 May 2010, the NCDATE parameter should be set to 2010-05-01 00:00:00 UTC.
```

and besides that it means you can't use GNU `date` to do timestep math on the result, e.g.:
` $ date -u -d '2018-01-01 00:00:00 UTC + 3600 sec'`
works but
` $ date -u -d '01-Jan-2018 03:00 + 3600 sec'`
doesn't.
(the above trick with `date` is a very handy for making time stamps for animations of fort.63 frames, given the start time from the .nc file and 1680000 or whatever seconds of the output timestep)

Matlab's datestr() does not like time zone info like "UTC" or "+0000", so that has to be added by hand. (and assumed to be true!)

[*] n.b. the underscores of Make_f15 links in the LaTeX doc have been UTF-8'd and so become hard to ctrl-f searched for

thanks,
Hamish

**Comment by krober10nd** [comment]
Hamish,

I agree that the start and end dates should match the netcdf file meta data.

I will change that.

Could you elaborate more on your first point? I'm not sure what you would
like to have modified.

**Comment by HamishB** [comment]
for the change in the first point see the patch above -- just to change the formatting of the output a bit:
```
-    fprintf(fid, '%16.9e %16.9e \n', f15dat.opealpha(k).val' ) ; 
+    fprintf(fid, '%16.9e %16.10g \n', f15dat.opealpha(k).val' ) ; 
```

It's a suggestion rather than a request, as it is mostly just to make my workflow a bit easier.

(any reason for the stray whitespace at the end of the line?)

**Comment by WPringle** [comment]
Hi Hamish, I agree on both counts. The NCDATE should also be in the isoformat as described for all the work I do so it would indeed be much better if it was the yyyy-mm-dd HH:MM:SS format.
Can you make a pull request for your changes. Thanks!

**Comment by krober10nd** [comment]
The handling of the date in the fort.15 is now resolved per pull request 33
