### ISSUE TITLE
Orthogonality

### ISSUE THREAD

**Issue by Bluerrror** [CHLNDDEV/OceanMesh2D#217]
I actually get stuck to generate a near pure orthogonal mesh. Can any one help me? I want to use this mesh in Delft3D-FM that constrained orthogonality to be lower than 0.5.

Best
Shahab

**Comment by krober10nd** [comment]
Could you share an example of what you achieve and where the condition is not met (and how you are measuring it) please?

**Comment by krober10nd** [comment]
Do you want to provide any more information here?

**Comment by Bluerrror** [comment]
Sorry far delay. Actually when I use RFGRID software of the DELFT3D, it always shows some elements that are not pure orthogonal.
