### ISSUE TITLE
Bathymetry interpolation

### ISSUE THREAD

**Issue by 123jk26** [CHLNDDEV/OceanMesh2D#219]
Bathymetry interpolation of mesh is not happening in Oceanmesh. Can you please tell me where I am wrong and where can I add this comment for interpolation?

**Comment by krober10nd** [comment]
In order to help you I need to see what you’re doing and what your inputs are. Simply saying it’s not working will not  really help anything.

**Comment by krober10nd** [comment]
Have you resolved your issue?
