### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#220]
* Issues should be posed in a standardized way with some form of example of what's not working on some clear explanation of what wants to be accomplished.
* All other examples failing to do this will be disregarding and inevitably deleted. 
* Issue template can be added following: https://github.com/stevemao/github-issue-templates

**Comment by CHLNDDEV** [comment]
This was updated in latest commit on Projection. Now the user has an option to do either a bug report or a feature request and still optionally ignore the two and file a blank issue.
