### ISSUE TITLE
‘msh.plot’ hold on option

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#222]
Enabling two plots to be visualized on the same figure similar to what happens with ‘geodata.plot()’

**Additional context**

none

**Comment by WPringle** [comment]
yeah it has that capability now. e.g., 

```
plot(m,'type','b')
plot(m,'type','bdnotri','holdon',1)
```

will plot the boundary on top of the bathymetry. Is what you are looking for?

**Comment by krober10nd** [comment]
Oh nice I forgot about this feature. Just plotting two triangulations to verify they line up in different colors. Can’t change the color of the triangles though but can trick it with changing the bathymetry field
