### ISSUE TITLE
Increasing the mesh resolution in the boundaries

### ISSUE THREAD

**Issue by Kasra-n90** [CHLNDDEV/OceanMesh2D#226]
Hi, I hope you are good.

In my case of mesh-generation, the boundaries are not that important. Therefore, I want to keep the resolution at that places quite high. However, based on my experience, we only can use 'max_el_ns' in edgefx function to determine the maximum resolution. Is here any way to determine the minimum resolution for the boundaries?

Thanks

**Comment by krober10nd** [comment]
Hey @Kasra-n90 the minimum mesh resolution is enforced in your meshing domain via the parameter `h0` that is passed to the `geodata` class constructor. 

The parameter `max_el_ns` limits the expansion of the shoreline resolution when using the feature size mesh resolution distribution.

**Comment by Kasra-n90** [comment]
Thank you for your kind answer. But, in my case, I want to have a fine resolution throughout my river (by using the channel scale ('ch' and 'channels' parameters) ) and a coarse resolution in my boundaries. However, the parameter 'h0', impacts the resolution throughout the river also. So is there any way to keep the resolution fine in river vicinity and have a coarse one in the boundaries?

Thanks again.

**Comment by krober10nd** [comment]
Then I would recommend creating a polygon around your channel area that you want to use fine resolution and using a different `h0` in that area than in the larger river. Use the multiscale approach.

 Note the `enforceMin` option in `meshgen`; this will allow you to not have to enforce the minimum edge length from all your domains.

**Comment by krober10nd** [comment]
Also, please next time try to use the issue templates and makes sure you answer the relevant questions. This will greatly help the process to help you!

**Comment by Kasra-n90** [comment]
Thank you for the kind answer...Yes, I will keep the template in mind next time!

**Comment by krober10nd** [comment]
Hey @Kasra-n90 if you have had success and can share any images of your problem or code, this would be useful to potentially help future users too in case they want to achieve similar things. 

Otherwise, can I close this issue?

**Comment by Kasra-n90** [comment]
I have another issue. Whenever, I want to separate a region and create a mesh inside that, my code does exclude that part and creates a mesh around that area.

For instance, here, I want to allocate a higher resolution to my river inside the basin. but as the second picture shows, the code has excluded the river and has created a fine mesh around it.
![image](https://user-images.githubusercontent.com/84328681/118740442-84637f00-b811-11eb-9180-d0225d4b4fcd.png)
![image](https://user-images.githubusercontent.com/84328681/118740408-6b5ace00-b811-11eb-9d80-723659606239.png)

For instance, if I have a shapefile of river like below picture, how should I define my 'bbox', so the mesh gets created inside the river.
![image](https://user-images.githubusercontent.com/84328681/118740576-d60c0980-b811-11eb-8713-237dead793a5.png)

Should I add all the code, shapefiles and DEM for better considering the issue?

Thank you for your time.

**Comment by krober10nd** [comment]
OM meshes regions defined by polygons so in your last image, the closed polygon is actually what is being meshed, which is the opposite of what you want.

Anyway, to mesh the river: in the inner domain's `geodata` object, switch the field `inpoly_flip` from it's existing value to the opposite. So if `inpoly_flip` is currently 1 for that domain, switch it to 0.

**Comment by krober10nd** [comment]
Has your issue been resolved? Can I close this?
