### ISSUE TITLE
CheckTimestep without pfix

### ISSUE THREAD

**Issue by brjoyce** [CHLNDDEV/OceanMesh2D#23]
Hi guys,

I was attempting to run CheckTimestep on a mesh without any fixed points. This gives me an error when it tries to clean up the mesh:
 Error in msh/CheckTimestep (line 1962)
                obj = clean(obj,'passive','proj',0,'pfix',pf,'con',con);

I fixed this on my own by just adding a        

    if ~isempty(obj.pfix)
                [pf(:,1),pf(:,2)] = m_ll2xy(obj.pfix(:,1),obj.pfix(:,2));
   else 
                  pf = [];
   end

around line 1936 as a quick fix, but I'm not sure if this is going to mess anything up within the code.

**Comment by krober10nd** [comment]
Nope this should be fine. Could you open a pull request for this small
change?

**Comment by WPringle** [comment]
Actually this is the exactly line I have in the dev branch. Perhaps forgot to copy it over to the Projection. Can you submit a pull request for this small change as Keith said?
