### ISSUE TITLE
Interpolating water depth for multiple scale mesh.

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#244]
**Describe the bug**
Hi @krober10nd  and @WPringle , I am curious about how does the function of interp() works in interpolating water depth to each vertice for a multiple scale mesh. The result I got seems odd. 

**To Reproduce**
I made a mesh covering two domains, the inner domain is the Pearl River Estuary, the outer domain is the North South China Sea. 
this is the mesh I generated:
![image](https://user-images.githubusercontent.com/66854878/125954315-f46773cb-12c8-493d-9643-20a5ebb01348.png)

for the inner domain, I use plot(gdat_PRE,'shp') and plot(gdat_PRE,'dem') to plot, get this two figures:
![image](https://user-images.githubusercontent.com/66854878/125954735-002273d5-4f45-46ec-8071-4588fd2b2f7f.png)
![image](https://user-images.githubusercontent.com/66854878/125954831-7d830ce2-9c0d-41d6-933b-f0d92cb4c65d.png)

The dem is a rectangularar area. The box of this inner domain I used is an arc line on the side of the sea.

After generating the integrated mesh, I used the interp() function to interpolate water depth to vertices.
m_NSCS_PRE = interp(m_NSCS_PRE,{gdat_NSCS,gdat_PRE},'type','depth','nan','fillinside','mindepth',1);

Well, then I used the script plot(m_NSCS_PRE,' type', 'blog'), see the figure below:
![image](https://user-images.githubusercontent.com/66854878/125959012-94116fe5-6300-4cdb-84bd-f65387f88c33.png)

The water depth in the log scale around the connected area seems odd. An obvious rectangular area appeared.

So, my question is that when using the interp() function to interpolate water depth to multiple scales mesh, the water depth used for the inner domain seems the whole rectangular dem domain, rather than the domain inside the arc line on the side of the sea. 

**Expected behavior**

So, I think the water depth interpolated into the inner domain should be bounded by the arc line rather than the whole dem of the inner domain.

I am not sure if my consideration is correct. Please check it.

**Screenshots/Figures**

**Configuration (please complete the following information):**
 - OS: [e.g. MacOS, Windows, Debian, etc.]
 - Version [e.g. OS Mojave]

**Additional context**

**Comment by krober10nd** [comment]
Hey Jiang 

Please don't use interpolation from `geodata` objects as they downsample the original data for the mesh size function creation. Use the original DEM in NetCDF format. 

Secondly, find the indices in your high resolution box and pass them to `interp` 
```
% bounds of high resolution area 
lon_min  =?? 
lat_min = ?? 
lat_max = ?? 
lon_max = ??
m_NSCS_PRE = interp(m_NSCS_PRE,dem1,'type','depth','nan','fillinside','mindepth',1);
k = find(m_NSCS_PRE.p(:,1) > lon_min &&  m_NSCS_PRE.p(:,1) < lon_max && m_NSCS_PRE.p(:,2) > lat_min && m_NSCS_PRE.p(:,2) < lat_max);   
m_NSCS_PRE = interp(m_NSCS_PRE,dem2,'type','depth','nan','fillinside','mindepth',1,'K',k);
```

**Comment by Jiangchao3** [comment]
Hi @krober10nd, Thanks for your reply. However, using the original DEM in NetCDF format file for interpolation just for the outer domain failed because out of the memory.

![image](https://user-images.githubusercontent.com/66854878/126020374-5b5a2e86-3db5-44b1-9a93-47487f801af4.png)

How should I avoid interpolating out of memory using the original dem NC file?

**Comment by krober10nd** [comment]
Yes I see. I would recommend looping over the DEM in longitudinal orientated slices using the K index option. Essentially doing the interpolation in sections.

**Comment by Jiangchao3** [comment]
Well, I will try this looping method you recommended. Seems using the DEM file to interpolation takes a longer run time than using the geodata.

Secondly, I also want to determine one more aspect: when interpolating for the inner high-resolution domain, whether the bounds of the interpolation is the bounds of the original DEM file‘ rectangle ’(because the DEM file is generated in a rectangular bound) rather than the custom arc bound designed by myself?

Because the NC dem file is generated by using a kriging interpolation method. Although the final dem file covers the whole rectangular area, the interpolated scatter data is only within the arc line area. So the water depth value out of the arc line area will be very inaccurate. Look at the followed figure:
![image](https://user-images.githubusercontent.com/66854878/126021323-a2053ffd-c475-4439-a6e1-c2db1d1d878a.png)

Maybe I can use the K index method by setting several lat_min values, these lat_min points can form such an arc line? And any other good suggestion?

Many thanks again!

**Comment by Jiangchao3** [comment]
Hi @krober10nd , this is my solution:

1、I use the extrac_subdomain function to extract the inner domain and the outer domain,
m_NSCS = extract_subdomain(m_NSCS_PRE,bbox_PRE,"keep_inverse",1);
plot(m_NSCS,'type','tri') 
m_PRE = extract_subdomain(m_NSCS_PRE,bbox_PRE);
plot(m_PRE,'type','tri');
![image](https://user-images.githubusercontent.com/66854878/126031012-7b1d4653-248a-43b5-bc54-f4696a403aae.png)
![image](https://user-images.githubusercontent.com/66854878/126031021-b212d539-495f-4cc6-a28f-462a2c1cd89a.png)

2、interepolate water depth for the inner domain and the outer domain respectively
for j = 1:length(k_index_NSCS)
    k_lon_min  = k_index_NSCS(j,1);
    k_lon_max =  k_index_NSCS(j,2);
    k_lat_min =  k_index_NSCS(j,3);
    k_lat_max =  k_index_NSCS(j,4);
    k = find(m_NSCS.p(:,1) >= k_lon_min & m_NSCS.p(:,1) < k_lon_max & m_NSCS.p(:,2) > k_lat_min & m_NSCS.p(:,2) < k_lat_max);
    m_NSCS = interp(m_NSCS,dem_NSCS,'type','depth','nan','fillinside','mindepth',1,'K',k);
    m_NSCS = interp(m_NSCS,dem_NSCS,'type','slope','slope_calc','rms','K',k);
end
    plot(m_NSCS,'type','blog')

for j = 1:length(k_index_PRE)
    k_lon_min  = k_index_PRE(j,1);
    k_lon_max =  k_index_PRE(j,2);
    k_lat_min =  k_index_PRE(j,3);
    k_lat_max =  k_index_PRE(j,4);
    k = find(m_PRE.p(:,1) >= k_lon_min & m_PRE.p(:,1) < k_lon_max & m_PRE.p(:,2) > k_lat_min & m_PRE.p(:,2) < k_lat_max);
    m_PRE = interp(m_PRE,dem_PRE,'type','depth','nan','fillinside','mindepth',1,'K',k);
    m_PRE = interp(m_PRE,dem_PRE,'type','slope','slope_calc','rms','K',k);
end
    plot(m_PRE,'type','blog');
![image](https://user-images.githubusercontent.com/66854878/126031072-09aa45b6-efed-4d3e-8e36-b6543b600f54.png)
![image](https://user-images.githubusercontent.com/66854878/126031082-a9f27d5f-28e0-4f62-9b4d-116bf6bf6822.png)

3、use the plus function to merge these two domain
m_NSCS_PRE_new = plus(m_PRE,m_NSCS,'match');
m_NSCS_PRE_new = lim_bathy_slope(m_NSCS_PRE_new,0.1,0);
plot(m_NSCS_PRE_new,'type','blog'); 
![image](https://user-images.githubusercontent.com/66854878/126031108-01182e04-1b12-4d1e-8c31-20cf6ee5842f.png)

This is the first time I know to use the K index option and looping method to interpolate water depth to the vertices. That method will be helpful for making a bigger mesh covering the whole IndWPac domain.

Have to admit that OceanMesh2d is so powerful, and you and William do great works.

I will be grateful if you can give some extra suggestions.

**Comment by krober10nd** [comment]
Glad you figured it out! I see what your problem was and that was a creative solution!
