### ISSUE TITLE
Hardlines in `edgefx`

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#248]
@Onur-Kurum adds the functionality to edit `edgefx` for better mesh sizing agreement around hardline constraints with variable point spacing in the mesh connectivity. 

Potentially, `meshgen` will also need to process a cell-array or NaN-delimited array composed of several hardlines. 

A hardline is a set of edges to-be-constrained in the mesh connectivity connected together by a set of fixed points. In OM parlance these are `egfix` and `pfix`  kwargs.

**Comment by CHLNDDEV** [comment]
#264
