### ISSUE TITLE
outgm in writefort15.m should be outgw?

### ISSUE THREAD

**Issue by shinbunya** [CHLNDDEV/OceanMesh2D#249]
**Describe the bug**
outgm in writefort15.m should be outgw?

**To Reproduce**
Invoke writefort15.m with a nonzero nws. This gives:
`Unrecognized field name "outgm".

Error in writefort15 (line 283)
    fprintf( fid, '%d %g %g %d', f15dat.outgm ) ;

Error in msh/write (line 255)
                    writefort15( obj.f15, [fname '.15'], obj.bd );`

**Expected behavior**
No error should be seen.

**Comment by shinbunya** [comment]
Or, outgw in readfort15.m should be outgm.

**Comment by WPringle** [comment]
Yes the `outgw` in `readfort15.m` should be `outgm`. 
That's strange, I remember changing this recently. It must not have been merged correctly.

**Comment by shinbunya** [comment]
Thanks!
