### ISSUE TITLE
No function named 'BoundCr'

### ISSUE THREAD

**Issue by AllenLan-mm** [CHLNDDEV/OceanMesh2D#255]
**Describe the bug**
Hi, @krober10nd 

When I am using OceanMesh2D and want to use the 'BoundCr' function to correct the mesh, it shows that BoundCr cannot be recognized. I also did not find the corresponding function in ‘msh.m’. But in the user guide and previous issues discussion, it seems that there is a BoundCr function. Is this a bug？

**Comment by krober10nd** [comment]
It was renamed when new functionality was added. 

It's now called bound_courant_number 

https://github.com/CHLNDDEV/OceanMesh2D/blob/07f98a9ed3ee60d226f2aa099317c1fb9005a484/%40msh/msh.m#L2778

**Comment by AllenLan-mm** [comment]
Thanks a lot.
