### ISSUE TITLE
storm surge simulation with riverine inflow in a hot start setup

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#258]
Hi @krober10nd, @WPringle and @zcobell 

This is the first time I simulate storm surge with riverine inflow in a hot start setup. Unfortunately, some errors occurred.
(Actually, I have simulated storm surge without riverine inflow in a hot start setup successfully in previous)

Just want to consult with you, many thanks for your patience.

**Firstly, I simulate the model in a cold start setup to get the fort.68.nc file. the start time and end time for the model run (only tide) and riverine inflow are as follows:**
cold start time:   ts='01-Aug-2017 06:00'; te='20-Aug-2017 06:00'

riverine inflow for cold start model:   ts='01-Aug-2017 06:00'; te='20-Aug-2017 06:00'

**Secondly, I want to simulate the storm surge with riverine inflow in a hot start setup**
hot start time:   ts='01-Aug-2017 06:00'; te='24-Aug-2017 12:00'

tropical cyclone starts from 2017082006 and ends at 2017082412

the NWS and WTIMNC option in Make_f15:  'NWS',8,'WTIMNC',[2017 08 01 06 1 0.9]

**riverine inflow for hot start model:  ts='20-Aug-2017 06:00'; te='24-Aug-2017 12:00'**

but some errors occurred as the attached log file shows.

**I guess that the conflict between the time of adcirc model and the time of riverine inflow causes this error.**

because the time step for a hot start model starts from '01-Aug-2017 06:00',  adcirc can get its hot start wind state automatically. **but it can not get the hot start state for the riverine inflow, right?**

**So I think I should give riverine inflow data from '01-Aug-2017 06:00' to '24-Aug-2017 12:00', covering the whole cold and hot start simulation. And adcirc just use the riverine inflow data from '20-Aug-2017 06:00' to '24-Aug-2017 12:00'**

In this way, I think the conflict in simulation time can be solved. I am not sure if I am correct.

Any suggestion about this issue? Many thanks to you!

Best wishes,
Jiangchao

[error.txt](https://github.com/CHLNDDEV/OceanMesh2D/files/7410413/error.txt)

**Comment by Jiangchao3** [comment]
> So I think I should give riverine inflow data from '01-Aug-2017 06:00' to '24-Aug-2017 12:00', covering the whole cold and hot start simulation. And adcirc just use the riverine inflow data from '20-Aug-2017 06:00' to '24-Aug-2017 12:00'

fortunately, in this way, the hot start storm surge model can run to the end successfully.

**Comment by krober10nd** [comment]
Hello Jiang, I would recommend you post this on the ADCIRC listserv. This is not an OceanMesh question.

**Comment by Jiangchao3** [comment]
Ok, thanks
