### ISSUE TITLE
make_bc error

### ISSUE THREAD

**Issue by carrey95** [CHLNDDEV/OceanMesh2D#260]
Hi, 
Can you please advise how to deal with below error message?
Thanks in advance.

>> m = make_bc(m,'auto',gdat,'distance'); % make the boundary conditions
Unrecognized function or variable 'land'.
Error in msh/make_bc (line 1357)
                                land = [land; inner];

**Comment by krober10nd** [comment]
I believe you need to pass a distance value after the kwarg distance. 

```
help msh.make_bc
```

**Comment by carrey95** [comment]
Thanks! I will try that.

- code : **gdat = geodata('shp',coastline,'bbox',bbox,'h0',min_el);**

After this code, I found **gdat.mainland =[]**. 
This means geodata did not automatically detect mainland?

**Comment by krober10nd** [comment]
Is your domain setup so that there are only islands? So then the shoreline would be fully enclosed by the bounding box. No parts would intersect it.

**Comment by carrey95** [comment]
Thanks for the comment. 
The issue is resolved by i) extending coastline somewhat arbitrarily so that there is no intersection with bounding box and manually closing the extended coastline, ii) thoroughly checking self-intersecting coastline of extremely small scale features (this occurred after ArcMap buffer and smoothing operation), and iii) further generalizing complicated features. 
Thanks again!
