### ISSUE TITLE
Invalid MEX-file, Access Denied

### ISSUE THREAD

**Issue by ablairification** [CHLNDDEV/OceanMesh2D#268]
When running `RunTests.m` or `Example_1_NZ.m` I get the following error:

`Invalid MEX-file 'C:\Work\OceanMesh2D\@ann\private\annmex.mexw64': Access is denied.`

I've attempted to open up the permissions on that file and directory, but it didn't help. 

Probably a very beginner's issue, but I haven't been able to find any leads on a fix.

**Comment by ablairification** [comment]
Sorry, Windows permission-ing was not working but I tried my Linux terminal and that seems to have worked!

Very excited to see if I can get this working for my needs, and stoked to see Python and Delft3D progress being made!

**Comment by krober10nd** [comment]
Thanks @ablairification Out of curiosity what version of Windows are you using and what version of MATLAB are you using?

**Comment by ablairification** [comment]
I'm running MATLAB R2020a on Windows 10 Enterprise version 21H2. It is an
enterprise 'managed' machine, so that may have something to do with the
permission issue. Also I should clarify that by 'Linux' I meant a MobaXterm
terminal where I could use chmod; I am much more *Nix command-line savvy
than Windows CLI!

Best,
Austen
