### ISSUE TITLE
speed up?

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#27]
The test to determine whether a given point is in/out of the meshing domain does not require the densified PSLG. Because the PSLG is by definition linear, the densification of points to h0/2 along the PSLG can only create new straight lines between two of the original points on the pslg. 

With this said, the densified PSLG is still necessary for the nearest distance calculation. However, a large savings may be obtained through the suggested optimization by reducing the inpoly execution time. This could especially benefit the multiscale method.

**Comment by WPringle** [comment]
Yes, I guess this needs to be tested carefully to make sure we don't get the problems that occurred last time without the densification of the PSLG, but it makes sense that we could do it just for the inpoly.

**Comment by krober10nd** [comment]
The idea is that the linear interpolation of points in between two original points of the domain cannot add any new information to the boundary description for the purposes of detecting if the point is in/out of the domain. 

Just need to create a branch and add the original PSLG to an attribute of the geodata class so that it is accessible deeper in the stack.

**Comment by krober10nd** [comment]
As a result of the polygon smoothing that takes place after the polygonal spacing is made to be less than h0/2, this technique is not a viable option.
