### ISSUE TITLE
Thalweg data format

### ISSUE THREAD

**Issue by 792753878xrc** [CHLNDDEV/OceanMesh2D#276]
hello ! OceanMesh2D is  awesome,! I have used for several times .
However I used it for generating the mesh of the area with sank slope by edgefx channel session.But I don't really understanding the thalweg data format,Could you please give me some information about it ,thanks so much!

**Comment by krober10nd** [comment]
I'm afraid this format is not document but if you load in the default channel thalweg mat file you can just repeat that format.
