### ISSUE TITLE
extra lines in fort.15 file!

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#279]
Hi @krober10nd and @WPringle 

I found that some new extra lines have been added into the fort.15 file when I update my OceanMesh2D code.

![image](https://user-images.githubusercontent.com/66854878/212911056-7691e4e7-3fd9-4074-9129-adabbe9660aa.png)

ADCIRC can not work when I use this fort.15 with extra lines 31725-31734.

The error shows:
![image](https://user-images.githubusercontent.com/66854878/212911623-b91b3f6c-e6e9-4e93-aaca-746c7a95c336.png)

But if I delete the extra lines 31725-31734, the ADCRIC can move forward. 

Have you encountered this error? And do these added extra lines have some certain meanings?

Thanks!

**Comment by WPringle** [comment]
@Jiangchao3 Yes, these are nameless options for adding a water level correction like mean sea level adjustments. I should have made the `FileName = 'null'` as default which would mean you don't need to delete the lines. Will make this PR. Thanks!

**Comment by Jiangchao3** [comment]
Thanks! @WPringle

**Comment by Jiangchao3** [comment]
Hi @WPringle, 

It is odd that an error occurs when I try to run adcirc model on a new linux machine, it says:

ERROR: read15: Could not read dynamicWaterLevelCorrectionControl namelist. The Fortran i/o error code was 5010.

When I delete the extra lines for dynamicWaterLevelCorrectionControl in fort.15, it works very well.

But in my previous HPC cluster, it can work with these dynamicWaterLevelCorrectionControl lines in fort.15.

If you know why, please let me know, many thanks!

**Comment by WPringle** [comment]
@Jiangchao3 I'm not quite sure why that would be (was it padcirc or adcirc?) but I made the PR #283  that makes getting these extra lines for the namelist optional (the user has to ask for it)

**Comment by Jiangchao3** [comment]
Hi @WPringle, the error of "ERROR: read15: Could not read dynamicWaterLevelCorrectionControl namelist. The Fortran i/o error code was 5010." occured when I tried to use adcprep to do the domain decomposition.

Actually, all is well on my previous HPC after you make a change in #272 to use a "null" as default.

The above error just occurred on my new machine, I am not sure if this is caused by the different system (i use ifort on my previous HPC, and use gfortran on my new machine).

So could you please Merge PR #283 as soon as possible, in this way, I can pull the updated code. Many thanks!

**Comment by WPringle** [comment]
@Jiangchao3 You can use the branch at PR #283 even if it is not merged. Just waiting for @krober10nd review to merge it in.

**Comment by Jiangchao3** [comment]
Thanks @WPringle, I will have a try.
