### ISSUE TITLE
startup.sh

### ISSUE THREAD

**Issue by chalolson** [CHLNDDEV/OceanMesh2D#294]
**Is your feature request related to a problem? Please describe.**

After reading your provided user guide, MatLab is not providing the opportunity to press the "Run" button (it is not green, its gray) on an unzipped version of the most current downloaded repository.

**Describe the solution you'd like**

Clearer (more effective) instructions on how to install OceanMesh2D

**Describe alternatives you've considered**

Not use OceanMesh2D

**Additional context**

**Comment by WPringle** [comment]
`setup.sh` needs be run from command line not Matlab. Then run the *.m files in the `Examples/` directory using Matlab to try out , or `RunTests.m` as described in Readme.

**Comment by krober10nd** [comment]
I honestly have no idea what you’re saying. Based on your question I’d strongly suggest you to use a different tool.
