### ISSUE TITLE
Issue regarding input files of ADCIRC model

### ISSUE THREAD

**Issue by jalal-90** [CHLNDDEV/OceanMesh2D#295]
Dear all,

I have created fort.14, fort.13, and fort.15 files for ADCIRC model using OceanMesh2D (https://github.com/CHLNDDEV/OceanMesh2D). But I cannot run the model, and am getting the following error.

forrtl: severe (27): too many records in I/O statement, unit -5, file Internal Formatted Write

Any suggestions would be appriciated. For your kind consideration, I added the input files in the attachment.

#adcirc #oceanmesh2d 

[input_files_ADCIRC.zip](https://github.com/CHLNDDEV/OceanMesh2D/files/12138083/input_files_ADCIRC.zip)

**Comment by WPringle** [comment]
@jalal-90 This is a bit outside scope of OceanMesh2D and more related to running ADCIRC. Suggest post a query to the ADCIRC listserv: `adcirc@listserv.unc.edu`  or check user manual or [ADCIRC wiki](https://wiki.adcirc.org/Main_Page)

**Comment by WPringle** [comment]
Outside scope of OM2D, suggested other channels.
