### ISSUE TITLE
How to specify the wind control and wind timestep parameters in Make_f15 function of OceanMesh2D?

### ISSUE THREAD

**Issue by jalal-90** [CHLNDDEV/OceanMesh2D#296]
Dear all,

I am sorry to bother you further. Actually, I need input data for Generalized Asymmetric Holland Model (GAHM) for ADCIRC model. In OceanMesh2D, there is a function (name Make_f15.m) to specify the wind control (NWS) and wind timestep (WTIMNC) parameters. I have the following required files for this purpose:
1.  fort.22 meteorological forcing file
2. preprocessing of the ATCF formatted track file using the ASymmetric Wind Input Preprocessor (aswip) program

The Make_f15.m function provides three ADCIRC input files (fort.13, fort.14, and fort.15).

I would like to know that how to add NWS and WTIMNC in the following line.
m = Make_f15( m, TS, TE, DT, 'tidal database', TPXO9, 'const', {CONST},'sta_database',{'CO-OPS','NDBC',[1]} ) ;

I would be very grateful to you if I can create the abovementioned input files accurately. 

Regards,
Jalal

#OceanMesh2D

**Comment by krober10nd** [comment]
Hi, 

They're additional kwarg arguments in `Make_f15`. All the available kwarg arguments can be see via the documentation `help Make_f15` 

```
m = Make_f15(...,'NWS',12,'WTIMNC',3600);
```
