### ISSUE TITLE
How to make the fort.22 file for ADCIRC model?

### ISSUE THREAD

**Issue by jalal-90** [CHLNDDEV/OceanMesh2D#297]
I have best track data from JTWC (https://www.metoc.navy.mil/jtwc/jtwc.html?western-pacific) over Northwestern Pacific Ocean. Now, I want to make a fort.22 format file. Is there an tool or script for this purpose?

https://adcirc.org/

#ADCIRC

**Comment by krober10nd** [comment]
This is not an OceanMesh issue.

**Comment by jalal-90** [comment]
> This is not an OceanMesh issue.

I did not post or mention for OceanMesh2D. Why does it seem for OceanMesh?
