### ISSUE TITLE
improve the elements quality

### ISSUE THREAD

**Issue by oceanywalker** [CHLNDDEV/OceanMesh2D#306]
I have successfully run the cases. While I found that some elements can't pass the 'element quality check' of SMS (e.g. the critical value of the element area change is 0.5 and some elements fail to pass it, see the figure)

**Comment by krober10nd** [comment]
Reduce the mesh gradation rate. With that said, this is an arbitrary test.

**Comment by oceanywalker** [comment]
![questions](https://github.com/CHLNDDEV/OceanMesh2D/assets/113840651/a43b35c6-3f96-4f59-b973-de3e860dd53b)
