### ISSUE TITLE
Plotting bathymetry for Example_8_AK 

### ISSUE THREAD

**Issue by aribal2018** [CHLNDDEV/OceanMesh2D#307]
Good morning,

I am trying to plot the bathymetry with proper axis for example_8_AK but was not successful.

The bathymetry can be plotted but I just could not fixed the axis.
This should be very simple one but I just could not figure it out.

Any suggestion will be greatly appreciated. 
Thank you very much.

**Comment by WPringle** [comment]
@aribal2018 please provide working example showing the problem. Preferably this should be moved to the Slack channel. Sign up [here](https://join.slack.com/t/oceanmesh2d/shared_invite/zt-2bxis3m9v-gYacwSgY1sd8mrRiif8LKA)

**Comment by aribal2018** [comment]
When we run the example, we get a perfect figure for the mesh as follows:
![image](https://github.com/CHLNDDEV/OceanMesh2D/assets/39908089/d305d276-66d4-45d8-8830-bb6d096ce9c7)

However, when I try to plot the bathymetry using command: plot(m,'type','bmesh'); % plot bathy on the mesh
Then, I get the following errors:
![image](https://github.com/CHLNDDEV/OceanMesh2D/assets/39908089/501fa993-7a04-44c0-8683-2d6c13d713ca)

where the figure is as follows:
![image](https://github.com/CHLNDDEV/OceanMesh2D/assets/39908089/465a06c3-7c63-4a31-b36c-5fff8e613b24)

I am expecting to obtain the figure as the mesh figure but for the bathymetry.
Hope this makes sense.

**Comment by WPringle** [comment]
@aribal2018 This makes sense now. It is having trouble because of cmocean pivot issue since your bathymetry doesn't go to zero. This may be a bug that deserves fixing. I'll take a look. But you can just manually type 'm_grid;' to get the lat-lon axis and manually update colormap to your desired settings as well.

**Comment by aribal2018** [comment]
Great..
Thanks

**Comment by krober10nd** [comment]
Check out the colormap kwarg argument in the plot method. The color limits aren't able to represent the range of colors in the subdomain you're plotting.

**Comment by aribal2018** [comment]
Thanks. I will check it.
This is still related to plot bathymetry.

Is the anyway to plot bathymetry based on the file fort.14?
I have created my final mesh but I forgot to plot the bathymetry.

However, I have the files *.14 and mesh file.
I believe the bathymetry can be plotted using those files but do not know how.
Thanks again. Your help is very much appreciated.

**Comment by WPringle** [comment]
use msh() command to read in fort.14 file. please see Matlab `help msh.msh` / user guide.

**Comment by aribal2018** [comment]
Thanks

**Comment by aribal2018** [comment]
Last question please for today,
I now could read the fort.14 but I still could not plot the bathymetry.  I think, I still miss something.
In my fort.14, I only have the following where proj, coord and others are all missing
![image](https://github.com/CHLNDDEV/OceanMesh2D/assets/39908089/435064fc-275a-492b-aeff-366d2e133b12)

Hence, when I try to plot the bathy with command: plot(m,'type','b'); % plot bathy on the mesh, it give me the following error messages:
![image](https://github.com/CHLNDDEV/OceanMesh2D/assets/39908089/e3bde09f-c90d-45a5-abb0-93689b426959)

Any suggestions?
Thanks again
