### ISSUE TITLE
How to set up parameters of hybrid bottom friction in OM

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#313]
Hi @krober10nd and @WPringle, 

I am wondering how to set up parameters for hybrid bottom friction in OM. The following is the description in the manual: 

If [NOLIBF](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#NOLIBF) = 2, the hybrid bottom friction formulation is used [FFACTOR](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#FFACTOR) = CF*[1+([HBREAK](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#HBREAK)/H)**[FTHETA](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#FTHETA)]**([FGAMMA](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#FGAMMA)/[FTHETA](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#FTHETA) and CF is as specified in this expression. Note, that [FFACTOR](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#FFACTOR) approaches CF in deep water (H > [HBREAK](https://adcirc.org/home/documentation/users-manual-v53/parameter-definitions#HBREAK)) and the hybrid friction formulation reverts to a standard quadratic formulation. This option is not available for friction coefficients specified using nodal attributes.

So four parameters is required, CF, HBREAK, FTHETA and FGAMMA. 

If I want to use this function, should I set one line CF = CF, HBREAK, FTHETA and FGAMMA to assign this four parameters when using Make_f15.m, or in other ways ?

Looking forward to your reply. Thanks very much.

Jiangchao

**Comment by Jiangchao3** [comment]
Just got it, it is easy to accomplish. Sorry for disturbing.

**Comment by krober10nd** [comment]
Maybe if you could post how you did it briefly here for others that would be helpful. Thanks!

**Comment by Jiangchao3** [comment]
Yes, 

When useing the hybrid bottom fraction, 

m.f15.bolibf = 2;
m.f15.taucf = [0.0025 2 10 1/3]; % [CF HBREAK FTHETA FGAMMA]
