### ISSUE TITLE
Issues while generating boundaries using make_bc

### ISSUE THREAD

**Issue by Jiangchao3** [CHLNDDEV/OceanMesh2D#320]
Hi @krober10nd and @WPringle,

I encountered an issue while generating boundaries using make_bc. Some parts of the mainland are incorrectly classified as islands. Despite adjusting various parameters in make_bc, including 'auto', 'auto_outer', 'both' ('depth', 'distance'), the problem persists.

the attached figure 1 show that geodata() correctly classify the shoreline into island and mainland, but why issue occured during the make_bc?

I currently just test it using the open public gebco and GSHHS_f_L1 dataset to generater the mesh.
(the issue first occured during I made mesh using personal shoreline and bathemetry, then I go to test the gebco and GSHHS_f_L1, I use the latest Version OceanMesh2D, I didn't see the simlar probloem in my previous mesh generation)

I’ve included the code and a screenshot for reference. Any advice would be greatly appreciated.

Best regards,
Jiangchao

`clearvars; clc;

%% Read into data
bbox_BoB             = xlsread('bbox_BoB'); 
bbox_Bangladesh      = [86.60 26.00;
                                    92.32 26.00;
                                    92.32 20.77;
                                    86.60 20.77;
                                    86.60 26.00];
dem_Bangladesh       = 'gebco_2022_n24.0_s8.0_w78.0_e100.0.nc';
coastline_Bangladesh = 'GSHHS_f_L1';

min_el_Bangladesh    = 250;   % Minimum resolution in meters.
max_el_Bangladesh   = 6000;  % Maximum resolution in meters.
grade_Bangladesh     = 0.25;  % Mesh grade in decimal percent.
R_Bangladesh           = 5;     % Number of elements to resolve feature width.

%% Process the geographical data 
gdat_Bangladesh = geodata('shp',coastline_Bangladesh,'dem',dem_Bangladesh,'bbox',bbox_Bangladesh,'h0',min_el_Bangladesh); 
% plot(gdat_Bangladesh,'shp');    % plot(gdat_Bangladesh,'dem');
%% Create edge function class for the Bangladesh domain
fh_Bangladesh = edgefx('geodata',gdat_Bangladesh,...
                        'max_el',max_el_Bangladesh,...
                             'g',grade_Bangladesh,...
                            'fs',R_Bangladesh);

rng(1.23456789);      % set a random seed to avoid some randomness for mesh generation
mshopts = meshgen('ef',fh_Bangladesh,'bou',gdat_Bangladesh,'plot_on',1,'nscreen',1,'proj','lam');

mshopts = mshopts.build; 

m_Bangladesh = mshopts.grd;

m_Bangladesh = interp(m_Bangladesh,dem_Bangladesh,'type','depth','nan','fillinside','mindepth',1);
m_Bangladesh = interp(m_Bangladesh,dem_Bangladesh,'type','slope','slope_calc','rms');

m_Bangladesh = renum(m_Bangladesh);

%plot(m_Bangladesh,'type','tri')
%plot(m_Bangladesh,'type','blog')`

m_Bangladesh = make_bc(m_Bangladesh,'auto_outer',gdat_Bangladesh);
%m_Bangladesh = make_bc(m_Bangladesh,'inner');
%m_Bangladesh = make_bc(m_Bangladesh,'auto',gdat_Bangladesh,'both',0.4,50);

**plot(gdat_Bangladesh,'shp');**
![image](https://github.com/user-attachments/assets/b0a692a2-cb0d-4797-8b4d-abd9b8e60c29)

**plot(m_Bangladesh,'type','bdnotri')**
![image](https://github.com/user-attachments/assets/18e0114a-9859-41db-ab96-39a1ec5a402f)

**zoom in on the interaction area between the 'red' and 'green'**
![image](https://github.com/user-attachments/assets/f78bdea6-5f08-41bb-ac80-f90ab36fab1f)

**Comment by krober10nd** [comment]
Probably GEBCO's depth nearshore isn't reliable. I would use the distance option in `make_bc` only and use the `distance` option.

**Comment by Jiangchao3** [comment]
thanks @krober10nd ,

the GEBCO depth would be not reliable, 

but even I did not use depth, only use distance, the issue still be there, 

`m_Bangladesh = make_bc(m_Bangladesh,'auto',gdat_Bangladesh,'distance',100*0.0023);` 

I test different parameter for the distance option, 

10*0.0023

100*0.0023
![image](https://github.com/user-attachments/assets/bf254040-94c5-49b2-ba4c-52efd22ebcb7)

1000*0.0023
![image](https://github.com/user-attachments/assets/f7fd0a5f-aa8b-465b-a91e-6e1bcf5bdec5)

**Comment by Jiangchao3** [comment]
Hi @krober10nd,

I guess I have found what happens for the boundary classification.

I compare the mesh I generated today (using the latest OceanMesh) and several previous meshes I generated long time ago (using old version, maybe 5.0).

**I found the msh.bd and msh.op slightly different** from using different version OM.

**this is my previous mesh** (mainland and island is well classified): 
![image](https://github.com/user-attachments/assets/686b9cec-93c9-4c4e-b332-de91270fe888)
**previous msh.bd.ibtype:**
![image](https://github.com/user-attachments/assets/27acdf1c-80e6-487c-9079-59aecfda9120)
**previous msh.op.ibtype:**
![image](https://github.com/user-attachments/assets/fd69fd19-d8f5-40ef-9481-fcb7b07a8a18)


**this is the current mesh** (issues occured in mainland):
![image](https://github.com/user-attachments/assets/14e3b628-35de-4aed-9a1b-ef6a4de45b81)
**current msh.bd.ibtype:**
![image](https://github.com/user-attachments/assets/cf71c2d5-29f4-4446-9ae0-cefe635f6f83)
**current msh.op.ibtype:**
![image](https://github.com/user-attachments/assets/86ea1f43-6f67-4fd6-84e9-c03170493499)

The right part in my current mesh, which should be in red (mainland) but show green is caused by its bd.ibtype equals to 0, if I change it to 20, the color will be in red, see the following mesh:

`m_Bangladesh.bd.ibtype(1) = 20;`

![image](https://github.com/user-attachments/assets/63b98684-725b-4815-9de4-b8510d6e9070)

I also go to check some of my previous mesh, I found that although the mainland (red) seems to have only one segment, but both of them does have two segments, both of their bd.ibtype equal to 20, no 0 exits. 

Although they show an green color, but they are not island, since the bd.ibtype island should be 21.

another concern is, in the current mesh, op.nbdv only have one column, as showing following, but the op.ibtype have more than one column, (0,20,.....), and is same with the bd.ibtype.

![image](https://github.com/user-attachments/assets/adccd213-62dd-40a0-aa88-00315dc9c449)

I just put these investigation here for your reference, I hope the logic makes sense. But I am not sure if simply using `m_Bangladesh.bd.ibtype(1) = 20;` is correct or not? Or still keep the bd.btype(1) = 0

Considering you can repeat it, I also test Example_1_NZ.m, the first bd.ibtype = 0

![image](https://github.com/user-attachments/assets/fd9f4be8-bea5-494a-aa27-6412bedad953)

![image](https://github.com/user-attachments/assets/e4eb28c8-6abb-4f47-9901-4c534d41ba1c)

after `m.bd.ibtype(1) = 20;`
![image](https://github.com/user-attachments/assets/a27ab532-5768-4902-a310-bf2265b39523)

Any advice would be greatly appreciated.

Best,
Jiangchao

**Comment by Jiangchao3** [comment]
hi @krober10nd, the easiest way to solve this problem is to change the plot code:                          

https://github.com/CHLNDDEV/OceanMesh2D/blob/0750c62af79cb81a1a3fd77ceedcae9d96365470/%40msh/msh.m#L511

elseif obj.bd.ibtype(nb)  == 20 || obj.bd.ibtype(nb)  == 0

otherwise, only ibtype = 20 will be plot in "red" as mainland, actually, ibtype = 0 also represents mainland
