### ISSUE TITLE
Export 2dm format file

### ISSUE THREAD

**Issue by q1165600785** [CHLNDDEV/OceanMesh2D#321]
I am a beginner in Matlab and I want to write a file as 2dm. I couldn't find it in the given example and I don't know how to do it. I want to publish it in the discussion forum, but it seems that I haven't developed it yet

**Comment by krober10nd** [comment]
```
% m = your msh obj
m.write(m,'my_mesh.2dm','2dm');
```

**Comment by q1165600785** [comment]
Thank you for your reply. Now I have exported a 2dm format file, but when I use pyfvcom to drive the tide level for grid boundary opening, I found that the generated 2dm boundary information does not include boundary information. It does contain ns field information. How can I solve this problem? I really need the help of experts

**Comment by q1165600785** [comment]
Thank you for your reply. Now I have exported a 2dm format file, but when I use pyfvcom to drive the tide level for the grid with open boundaries, I found that the generated 2dm boundary information does not include open boundary information, and there is no ns field information inside. How can I solve this problem? I really need the help of experts

**Comment by krober10nd** [comment]
That's a different issue be beyond the scope of this program.
