### ISSUE TITLE
No open Boundary Nodes in fort.14 while using Example_6b_GBAY_w_floodplain.m

### ISSUE THREAD

**Issue by SuRu-1310** [CHLNDDEV/OceanMesh2D#322]
Sir/Madam,
i am using Example_6b_GBAY_w_floodplain.m to generate mesh file (fort.14) for ADCIRC model input. Here output is good, but when i open that file, i found that there is no open Boundary nodes, i.e. open boundary nodes = 0 in this file.
so far i have used datasets from this link https://zenodo.org/records/2605388.
Also i have used seperately GEBCO-2024 data, But in both case no open boundary nodes are generated so far.
It will be pleasure if you help me out.
Thanks.

**Comment by WPringle** [comment]
> Sir/Madam, i am using Example_6b_GBAY_w_floodplain.m to generate mesh file (fort.14) for ADCIRC model input. Here output is good, but when i open that file, i found that there is no open Boundary nodes, i.e. open boundary nodes = 0 in this file. so far i have used datasets from this link https://zenodo.org/records/2605388. Also i have used seperately GEBCO-2024 data, But in both case no open boundary nodes are generated so far. It will be pleasure if you help me out. Thanks.

Yes, that is because the `make_bc` function is not called in the example. You can just add this call manually to your example to create boundary nodes following the Matlab help instructions.
