### ISSUE TITLE
error in ParseShoreline

### ISSUE THREAD

**Issue by jveeramon** [CHLNDDEV/OceanMesh2D#33]
I am testing out the mesh generation software and I am getting the following error when running Example_1_NZ using m_map 1.4 and Matlab 2017a on a windows laptop. Any help is much appreciated.

Reading shapefile with m_shaperead
179837 Records in file, by 500:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
.......................................................................................................................................................................................................................................................................................................................................................................Partitioning the boundary into islands, mainland, ocean
Index exceeds matrix dimensions.
Error in Read_shapefile (line 149)
           tmpCC{nn,2} = tmpC{ii,2};
Error in geodata/ParseShoreline (line 276)
                polygon_struct = Read_shapefile( obj.contourfile, [], ...
Error in geodata (line 240)
            obj = ParseShoreline(obj) ;
Error in Example_1_NZ (line 17)
gdat = geodata('shp',coastline,'bbox',bbox,'h0',min_el);

**Comment by jveeramon** [comment]
Doing a little more digging resulted in the following:

S = m_shaperead(fname{1},reshape(bboxt',4,1));

results in a 421x1 structure S, with one field "points". So,
>> size(tmpC{ii})
ans =
       37219           2
>> size(tmpC{ii,2})
Index exceeds matrix dimensions.

**Comment by krober10nd** [comment]
I suspect the shapefile has not been read into the workspace correctly and the struct2cell command doesn't  convert it correctly (on line 134) in Read_shapefile.. At line 65 in read_shapefile, can you see if it goes into the first clause of the if statement? That's what it does for me. Also, did you download all the components of gshhs and place them all in the same directory (e.g., .shp, .dbf and .shx files?) 

`             if isfield(S,'dbf')  `
`                   code = S.dbfdata(:,1); `
 `                   S = cell2struct([D code]',{'points' 'type'},1);`
`                else`
   `                 S = cell2struct(D','points',1);`
  `              end`

**Comment by jveeramon** [comment]
You are correct. It does not go to the first if clause. My dataset directory structure is
C:\Users\veeramon\Documents\MATLAB\OceanMesh2D\datasets\GSHHS_shp\f\
and the GSHHS_f_L1.dbf, GSHHS_f_L1.prj, and GSHHS_f_L1.shp files are there.

PS C:\Users\veeramon\Documents\MATLAB\OceanMesh2D\datasets\GSHHS_shp\f> dir GSHHS_f_L1*


    Directory: C:\Users\veeramon\Documents\MATLAB\OceanMesh2D\datasets\GSHHS_shp\f


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/14/2017  10:27 PM       38125670 GSHHS_f_L1.dbf
-a----        6/14/2017  10:27 PM            143 GSHHS_f_L1.prj
-a----        6/14/2017  10:27 PM      161320396 GSHHS_f_L1.shp
-a----        6/14/2017  10:27 PM        1438796 GSHHS_f_L1.shx

Any quick thoughts on how to fix it?

**Comment by jveeramon** [comment]
Further investigation in m_shaperead, right before reading the shapefile,:

K>> M
M = 
  struct with fields:

         version: 1000
      shape_type: 5
            MBRx: [2×1 double]
            MBRy: [2×1 double]
            MBRz: [2×1 double]
            MBRm: [2×1 double]
    filelength16: 719398
            type: NaN
           ctype: ' '
            ncst: []
             mbr: [179837×4 double]
      dbfversion: 3
         dfbdate: [2017 6 15]
      fieldnames: {1×6 cell}
         dbfdata: {179837×6 cell}
              id: {179837×1 cell}
           level: {179837×1 cell}
          source: {179837×1 cell}
       parent_id: {179837×1 cell}
      sibling_id: {179837×1 cell}
            area: {179837×1 cell}

So, there is no field called dbf, only dbfdata. Would that be the problem?

**Comment by krober10nd** [comment]
Yes, my record is quite different using the same version of m_map. Maybe this has to do with the endian-ness of the machine..I assume your machine is 64-bit?

 In any case, I believe this is a problem with m_map. Perhaps lets look at other users of m_map to see if they have similar problems? 

`M = 

  struct with fields:

         version: 1000
      shape_type: 5
            MBRx: [2×1 double]
            MBRy: [2×1 double]
            MBRz: [2×1 double]
            MBRm: [2×1 double]
    filelength16: 719398
            type: 5
           ctype: 'polygon'
            ncst: {[]}
             mbr: [179837×4 double]
      dbfversion: 3
         dfbdate: [2017 6 15]
      fieldnames: {'id'  'level'  'source'  'parent_id'  'sibling_id'  'area'}
         dbfdata: {179837×6 cell}
             dbf: [1×1 struct]`

**Comment by jveeramon** [comment]
So I added a line:
S.dbf = S.dbfdata; 
right before the id isfield(S,'dbf') line 

and I was able to generate the mesh... Hmm

![NZ](https://user-images.githubusercontent.com/40062816/69017114-524a3600-096a-11ea-82ad-68c658b204ff.jpg)

**Comment by krober10nd** [comment]
Nice, Jay. That's good to see. You made this modification inside m_map right? What's the line number?

**Comment by jveeramon** [comment]
Actually, I did it in read_shapefile

Changed line 65 from

                if isfield(S,'dbf')

to                 if isfield(S,'dbf') || isfield(S,'dbfdata')

**Comment by krober10nd** [comment]
Ok, thanks. That's an easy fix. Like I said earlier, we've had other users report this but I was never able to replicate the issue on my machines so I couldn't fix it. I just opened a pull request.

**Comment by jveeramon** [comment]
Awesome. Glad to be of help. Since I am not that familiar with git (I typically use svn), let me know if you need anything from me. I believe I downloaded the Oceanmesh2D as a zip file and moved m_map and the datasets that you shared into the directory.
