### ISSUE TITLE
Mainland/sea boundary detection

### ISSUE THREAD

**Issue by javirg** [CHLNDDEV/OceanMesh2D#4]
Is there any way to force the program to mesh a selected side of the shapefile?

In some cases, I got meshed the land surface instead of the water one.

![meshed_land](https://user-images.githubusercontent.com/12843025/56066141-e5701d00-5d44-11e9-8b3e-f5661ab0d351.png)
![meshed_water](https://user-images.githubusercontent.com/12843025/56066252-35e77a80-5d45-11e9-973d-f5331b5c46c8.png)

**Comment by krober10nd** [comment]
Yes, change the value of the attribute "inpoly_flip" in your geodata class instance from either 0 to 1 or 1 to 0. Sometimes these incorrect oceanside detections occur when the shapefile isn't a polygon.

**Comment by javirg** [comment]
Allright, thanks.

I used the same shapefile on both examples shown in the pictures. Only changing the bounding box caused to mesh either land or sea.

**Comment by WPringle** [comment]
The updated _geodata_ may have better luck dealing with this automatically. We have a test in _check_connectedness_inpoly_ function which compares the inpoly on your inputs to the inpoly versus a light version of GSHHS. If the test is inconsistent the inpoly_flip is set to 1. It was only enabled for bad unconnected polygons but I enabled this for all polygons now.
