### ISSUE TITLE
Msh.cleaning destroys previous bathy

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#40]
If you execute msh.clean, the routine will not correctly map you bathymetry back onto the msh vertices correctly.

**Comment by WPringle** [comment]
The fixmeshandcarry routine now ensure that bathymetry is mapped back correctly.
But I wonder about the bound_con_int routine if that does it properly?

**Comment by krober10nd** [comment]
You mean if you call it separately and not from within msh.clean? 

I suppose we could put a fixmeshandcarry call at the end of bound_conn_init? Ideally, the user will want to preserve bathymetry as easily as much as possible when doing mesh improvements.

**Comment by WPringle** [comment]
No i mean call within msh.clean. We can easily test this but yeah need to make sure the bathy is carried over in bound_con_int then msh.clean will perform as desired.

**Comment by krober10nd** [comment]
has this been tested any further?

**Comment by krober10nd** [comment]
With the fixmeshandcarry this no longer is a bug.
