### ISSUE TITLE
Output msh as vtk/vtu files

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#41]
A new file format for write should be added called vtu and vtk. This enables users to visualize their meshes inside Paraview and for solvers like FireDrake. The former visualization software is quite efficient compared to MATLAB's visualization capabilities. 

For example this MathWork's submission is particularly good. https://www.mathworks.com/matlabcentral/fileexchange/47814-vtkwrite-exports-various-2d-3d-data-to-paraview-in-vtk-file-format

**Comment by WPringle** [comment]
Should we just pass this onto pyOceanMesh?

**Comment by krober10nd** [comment]
Yep.  it will be trivial with some existing packages in python.
