### ISSUE TITLE
Rename makens to make_boundaries

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#47]
I propose to rename the msh method makens to make_boundaries for easier understanding.

**Comment by WPringle** [comment]
Yes, or make_bcs? make_boundaryconditions?

**Comment by krober10nd** [comment]
probably make_bc is best. Most people understand the acronym bc.

**Comment by WPringle** [comment]
Or I'm thinking now it should be make_bd to match the plot('bd') and bd attribute in the msh class.

**Comment by krober10nd** [comment]
This is finally addressed in #67.
