### ISSUE TITLE
Mesh boundaries doesn't assign correctly using interpFP

### ISSUE THREAD

**Issue by ArslaanK** [CHLNDDEV/OceanMesh2D#48]
Hi,
I have been trying to create the mesh boundaries using "makens" at the end of mesh workflow and noticed too issues/glitches , may be you guys can take a look at it.

1. For the entire North Atlantic mesh we noticed that it create 1200+ mainland nodestrings using the "auto" option and the only possible way around we figured out was to use "islands" option. That way we will load the mesh in SMS and delete the most outer island to recreate mainland and ocean boundary only.

2. Using the interpFP interpolation scheme and later assigning the mesh boundaries using "makens" for the small rivers like Potomac, it will not recognize the ocean and mainland boundary. And it assigns only the island boundaries by using "auto" or "islands".
`meshFull_FP = interpFP(meshFull,gdatovFull,muwFull,gdatuwFull,0.05,0); 
`
It will be great if you kindly take a look at it.
Thanks

**Comment by krober10nd** [comment]
Hey Arslaan, 

You can manually click the start and end points of a boundary using the makens(m,'outer',0) option where 0 is the direction (0 for CW and 1 for CCW). 

Normally, I would specify islands first, then do outer to get the mainland and ocean boundary specified. 

If you could post the code or share through email I can help out with the auto option and the interpFP?

**Comment by ArslaanK** [comment]
I will share the code as I can't seem to post figures for better understanding. Can you share your email here?
I just used the makens(m,'outer',0) option , however it doesn't get the vstart and vend end value even when using the data cursor.

**Comment by krober10nd** [comment]
my email is krober@usp.br 

When the figure pops up, click the drop down menu saying "Tools" ---> "Data cursor" Then hover over the nodes on the mesh boundary that you want to start at, type the index in MATLAB of vstart and then repeat with vend.

**Comment by ArslaanK** [comment]
thanks for the guidance in resolving the issue.
