### ISSUE TITLE
Errors in user guide

### ISSUE THREAD

**Issue by javirg** [CHLNDDEV/OceanMesh2D#5]
In `\subsection{Around the world: \textit{Example\_1\_NZ.m}}` code example, you call the variable `min_res` wich does not exist.

In `\subsubsection{Methods}`, the third element in list has a broken reference `Section \ref(sec:).`

**Comment by krober10nd** [comment]
I fixed the first one. The second one has been a work in progress as the clean method was moved to the msh class as of V2.0. I am actively documenting the msh class methods (there are dozens) and it's a lot of work.

**Comment by javirg** [comment]
Thanks!
