### ISSUE TITLE
Overloaded plot hold optional 

### ISSUE THREAD

**Issue by krober10nd** [CHLNDDEV/OceanMesh2D#72]
Would be nice to have `plot` have one more option to ‘hold on’. By default all plot options should create a new figure but sometimes you want to plot on top of different plots.

**Comment by WPringle** [comment]
I think that we should also make geodata `plot` make a new figure by default but add the `hold on' option.

**Comment by krober10nd** [comment]
Yes, `geodata` makes a new figure and the rest have the option to `hold on`.

**Comment by krober10nd** [comment]
#77 resolves this.
