### ISSUE TITLE
User-specified edge function

### ISSUE THREAD

**Issue by sbrus89** [CHLNDDEV/OceanMesh2D#83]
Hi @krober10nd and @WPringle,

I was wondering if you guys would be interested in adding the ability to input user-defined edge functions. I wrote a bit of crude code to do this in OceanMesh2D and am happy to share it back to the repo. If you're interested, I can open a PR. If not, no big deal at all!

**Comment by krober10nd** [comment]
Hey @sbrus89 absolutely. All contributions are very welcome! I think the PR is the best way to do that.

**Comment by sbrus89** [comment]
@krober10nd, Sounds good. I'll need you guys' feedback on the implementation etc. I'll start a PR next week.

**Comment by WPringle** [comment]
Yes that sounds good. 

Technically the user can already generate meshes using an arbitrary edge function by editing the  interpolant of the edgefx class. But it would be good to formalize this through a call to edgefx without any inputs [edgefx()] to produce a blank edgefx class which the user can then fill with the interpolant of their choice. 

Or do you have in mind something different like an arbitrary function handle passed to edgefx?

**Comment by krober10nd** [comment]
In theory, the simplest thing you should be able to do is pass an anonymous function handle that's your isotropic mesh function, a signed distance function representing your domain, and a minimum mesh size. I haven't done that in a while but perhaps that functionality has been broken.

**Comment by krober10nd** [comment]
@sbrus89 do you still plan to contribute something or can I close this?

**Comment by sbrus89** [comment]
@krober10nd, thanks for pinging me on this. See #96.

**Comment by krober10nd** [comment]
Closed due to inactivity.
