### ISSUE TITLE
Mixed triangular-quad elements & curved open boundary

### ISSUE THREAD

**Issue by huyquangtranaus** [CHLNDDEV/OceanMesh2D#89]
Hi @krober10nd  and @WPringle,

I am wondering if oceanmesh2D can handle mixed (tri and quad) grids and curved lines for open boundaries (instead of a rectangular box) as done in SMS? or is there any idea to make it possible?

Thanks a lot :)

Cheers,
Huy

**Comment by krober10nd** [comment]
1. Currently, no we cannot handle mixed tri and quad grids. 

2. In regard to the curved boundary, yes. If you pass a planar straight line graph ('pslg') as the bbox, it can be any shape. 

```
gdat = geodata('shp',shapefile,'bbox',[x0,y0; x1,y1; x2,y2,....,xN,yN]); 
```
where ``x0,y0`` are coordinates of the polygonal box you want.

**Comment by huyquangtranaus** [comment]
That is awesome, Keith @krober10nd.  Thanks
